Virtus: TestNode Class Reference
TestNode Class Reference
#include <TestNode.h>
Public Member Functions
TestNode ()
~TestNode ()
void update (float seconds)
void draw (Camera *cam)
bool load (const char *Filename)
Private Attributes
Shader * nodeShader
VertexSet * nodeVertexSet
Texture * nodeTexture
char * nodeName
Detailed Description
Definition at line 9 of file TestNode.h.
Constructor & Destructor Documentation
TestNode::TestNode ()
Definition at line 64 of file TestNode.cpp.
References Filesystem::evaluateChild(), GRenderer::getGraphicsAPI(), GRenderer::getRenderer(), Filesystem::getRoot(), GraphicsAPI::getShaderFactory(), TextureMonitor::getTexture(), GRenderer::getTextureMonitor(), ShaderFactory::loadShader(), GraphicsAPI::newVertexSet(), nodeName, nodeShader, nodeTexture, nodeVertexSet, VertexSet::setNormals(), Shader::setNumberOfTextures(), VertexSet::setTextureCoordinates(), Shader::setTextureName(), and VertexSet::setVertices().
TestNode::~TestNode ()
Definition at line 91 of file TestNode.cpp.
References GRenderer::getRenderer(), GRenderer::getTextureMonitor(), nodeName, nodeShader, nodeTexture, and TextureMonitor::releaseTexture().
Member Function Documentation
void TestNode::draw (Camera * cam) [virtual]
Reimplemented from SceneNode.
Definition at line 109 of file TestNode.cpp.
References Shader::activateShader(), Shader::deactivateShader(), VertexSet::Draw(), GRenderer::getGraphicsAPI(), GRenderer::getRenderer(), Vector3f::getX(), Vector3f::getY(), Vector3f::getZ(), LightAmbient, LightDiffuse, LightPosition, SceneNode::m_position, SceneNode::m_rotation, nodeShader, nodeTexture, nodeVertexSet, GraphicsAPI::popMatrix(), GraphicsAPI::pushMatrix(), GraphicsAPI::rotateMatrix(), Shader::setTexture(), and GraphicsAPI::translateMatrix().
bool TestNode::load (const char * Filename)
Definition at line 201 of file TestNode.cpp.
References nodeName, nodeVertexSet, VertexSet::setIndices(), VertexSet::setNormals(), VertexSet::setTextureCoordinates(), and VertexSet::setVertices().
Referenced by ModelViewer::onLoad().
void TestNode::update (float seconds) [virtual]
Reimplemented from SceneNode.
Definition at line 142 of file TestNode.cpp.
Member Data Documentation
char* TestNode::nodeName [private]
Definition at line 16 of file TestNode.h.
Referenced by load(), TestNode(), and ~TestNode().
Shader* TestNode::nodeShader [private]
Definition at line 12 of file TestNode.h.
Referenced by draw(), TestNode(), and ~TestNode().
Texture* TestNode::nodeTexture [private]
Definition at line 14 of file TestNode.h.
Referenced by draw(), TestNode(), and ~TestNode().
VertexSet* TestNode::nodeVertexSet [private]
Definition at line 13 of file TestNode.h.
Referenced by draw(), load(), and TestNode().
The documentation for this class was generated from the following files:
Code/Render/3D/TestNode.h
Code/Render/3D/TestNode.cpp