Virtus: VertexSet Class Reference
VertexSet Class Reference
#include <VertexSet.h>
Public Member Functions
virtual ~VertexSet ()
virtual void setVertices (float *vertices, unsigned int number)=0
virtual void setNormals (float *normals, unsigned int number)=0
virtual void setTextureCoordinates (float *tcoords, unsigned int number)=0
virtual void setColourValues (float *cvals, enum ColourValueTypes type, unsigned int points)=0
virtual void setIndices (unsigned int *indices, unsigned int numberPoints)=0
virtual float * getVertices ()=0
virtual float * getNormals ()=0
virtual float * getTextureCoordinates ()=0
virtual float * getColourValues ()=0
virtual unsigned int * getIndices ()=0
virtual void Draw ()=0
virtual void Draw (unsigned int start_vertex, unsigned int num_Vertices, PrimitiveTypes type)=0
virtual unsigned int getNumVertices ()=0
virtual unsigned int getNumNormals ()=0
virtual unsigned int getNumTextureCoordinates ()=0
virtual unsigned int getNumColourValues ()=0
virtual unsigned int getNumIndices ()=0
Detailed Description
Definition at line 22 of file VertexSet.h.
Constructor & Destructor Documentation
virtual VertexSet::~VertexSet () [inline, virtual]
Definition at line 28 of file VertexSet.h.
Member Function Documentation
virtual void VertexSet::Draw () [pure virtual]
Implemented in GL2VertexSet.
Referenced by WorldNode::draw(), TestNode::draw(), TerrainPatch::draw(), Plane::draw(), InterfaceLayer::drawQuad(), InterfaceLayer::drawQuadWithUIElement(), and FontMap::Render().
virtual void VertexSet::Draw (unsigned int start_vertex, unsigned int num_Vertices, PrimitiveTypes type) [pure virtual]
Implemented in GL2VertexSet.
virtual float* VertexSet::getColourValues () [pure virtual]
Implemented in GL2VertexSet.
virtual unsigned int* VertexSet::getIndices () [pure virtual]
Implemented in GL2VertexSet.
virtual float* VertexSet::getNormals () [pure virtual]
Implemented in GL2VertexSet.
virtual unsigned int VertexSet::getNumColourValues () [pure virtual]
Implemented in GL2VertexSet.
virtual unsigned int VertexSet::getNumIndices () [pure virtual]
Implemented in GL2VertexSet.
virtual unsigned int VertexSet::getNumNormals () [pure virtual]
Implemented in GL2VertexSet.
virtual unsigned int VertexSet::getNumTextureCoordinates () [pure virtual]
Implemented in GL2VertexSet.
virtual unsigned int VertexSet::getNumVertices () [pure virtual]
Implemented in GL2VertexSet.
virtual float* VertexSet::getTextureCoordinates () [pure virtual]
Implemented in GL2VertexSet.
Referenced by InterfaceLayer::drawQuad(), and InterfaceLayer::drawQuadWithUIElement().
virtual float* VertexSet::getVertices () [pure virtual]
Implemented in GL2VertexSet.
Referenced by InterfaceLayer::drawQuad(), InterfaceLayer::drawQuadWithUIElement(), and FontMap::Render().
virtual void VertexSet::setColourValues (float * cvals, enum ColourValueTypes type, unsigned int points) [pure virtual]
Implemented in GL2VertexSet.
Referenced by InterfaceLayer::InterfaceLayer(), and Plane::Plane().
virtual void VertexSet::setIndices (unsigned int * indices, unsigned int numberPoints) [pure virtual]
Implemented in GL2VertexSet.
Referenced by TestNode::load().
virtual void VertexSet::setNormals (float * normals, unsigned int number) [pure virtual]
Implemented in GL2VertexSet.
Referenced by TestNode::load(), and TestNode::TestNode().
virtual void VertexSet::setTextureCoordinates (float * tcoords, unsigned int number) [pure virtual]
Implemented in GL2VertexSet.
Referenced by WorldNode::f_calculateVertices(), FontMap::FontMap(), TerrainPatch::generateDrawLOD(), InterfaceLayer::InterfaceLayer(), TestNode::load(), and TestNode::TestNode().
virtual void VertexSet::setVertices (float * vertices, unsigned int number) [pure virtual]
Implemented in GL2VertexSet.
Referenced by WorldNode::f_calculateVertices(), FontMap::FontMap(), TerrainPatch::generateDrawLOD(), InterfaceLayer::InterfaceLayer(), TestNode::load(), Plane::Plane(), and TestNode::TestNode().
The documentation for this class was generated from the following file:
Code/Render/GraphicsAPI/VertexSet.h