Virtus: FREngine Class Reference
FREngine Class Reference
#include <FREngine.h>
Public Member Functions
FREngine ()
~FREngine ()
bool Init ()
bool Load (File *file)
void LoadFontmap (int PointSize)
void Render (int PointSize, unsigned int X, unsigned int Y, std::string Line)
void Render (int PointSize, unsigned int X, unsigned int Y, unsigned int drawWidth, unsigned int drawHeight, std::string Line)
void Cleanup ()
void SetFontPointSize (int Point)
void SetFontPixelSize (int Pixels)
Public Attributes
std::vector< FontMap > FontMaps
Private Member Functions
int NextPowerTwo (int X)
Private Attributes
FT_Library Library
FT_Face FontFace
FT_GlyphSlot GlyphSlot
Static Private Attributes
static const char * TAG = "Font Render Engine"
Detailed Description
Definition at line 12 of file FREngine.h.
Constructor & Destructor Documentation
FREngine::FREngine ()
Definition at line 7 of file FREngine.cpp.
References Init().
FREngine::~FREngine ()
Definition at line 13 of file FREngine.cpp.
References Cleanup().
Member Function Documentation
void FREngine::Cleanup ()
Definition at line 248 of file FREngine.cpp.
References FontMaps, GRenderer::getRenderer(), GRenderer::getRenderLog(), Library, TAG, and LogWriter::writeLine().
Referenced by ~FREngine().
bool FREngine::Init ()
Definition at line 19 of file FREngine.cpp.
References GRenderer::getRenderer(), GRenderer::getRenderLog(), Library, TAG, and LogWriter::writeLine().
Referenced by FREngine().
bool FREngine::Load (File * file)
Definition at line 32 of file FREngine.cpp.
References File::createInputStream(), fileId, FontFace, FilesystemNode::getName(), GRenderer::getRenderer(), GRenderer::getRenderLog(), File::getType(), GlyphSlot, File::length(), Library, DataInputStream::open(), DataInputStream::read(), TAG, and LogWriter::writeLine().
Referenced by GEngine::initialize(), and InterfaceLayer::InterfaceLayer().
void FREngine::LoadFontmap (int PointSize)
Definition at line 94 of file FREngine.cpp.
References FontChar::AdvanceX, FontChar::CharHeight, FontMap::CharList, FontChar::charTexture, FontChar::CharWidth, FontFace, FontMaps, GRenderer::getGraphicsAPI(), GRenderer::getRenderer(), GlyphSlot, FontChar::Height, input_data_byte_luminance_alpha, Texture::loadTextureData(), GraphicsAPI::newTexture(), NextPowerTwo(), FontChar::OffsetX, FontChar::OffsetY, FontMap::PointSize, SetFontPointSize(), and FontChar::Width.
Referenced by Render().
int FREngine::NextPowerTwo (int X) [private]
Definition at line 270 of file FREngine.cpp.
Referenced by LoadFontmap().
void FREngine::Render (int PointSize, unsigned int X, unsigned int Y, unsigned int drawWidth, unsigned int drawHeight, std::string Line)
Definition at line 188 of file FREngine.cpp.
References FontChar::AdvanceX, FontChar::CharHeight, FontMaps, FontChar::Height, LoadFontmap(), FontChar::OffsetX, FontChar::OffsetY, and FontChar::Width.
void FREngine::Render (int PointSize, unsigned int X, unsigned int Y, std::string Line)
Definition at line 147 of file FREngine.cpp.
References FontChar::AdvanceX, FontMaps, and LoadFontmap().
Referenced by Button::draw(), ViewerUserInterface::draw(), and InterfaceLayer::drawText().
void FREngine::SetFontPixelSize (int Pixels)
Definition at line 266 of file FREngine.cpp.
References FontFace.
void FREngine::SetFontPointSize (int Point)
Definition at line 262 of file FREngine.cpp.
References FontFace.
Referenced by LoadFontmap().
Member Data Documentation
FT_Face FREngine::FontFace [private]
Definition at line 20 of file FREngine.h.
Referenced by Load(), LoadFontmap(), SetFontPixelSize(), and SetFontPointSize().
std::vector<FontMap> FREngine::FontMaps
Definition at line 15 of file FREngine.h.
Referenced by Cleanup(), LoadFontmap(), and Render().
FT_GlyphSlot FREngine::GlyphSlot [private]
Definition at line 21 of file FREngine.h.
Referenced by Load(), and LoadFontmap().
FT_Library FREngine::Library [private]
Definition at line 19 of file FREngine.h.
Referenced by Cleanup(), Init(), and Load().
const char * FREngine::TAG = "Font Render Engine" [static, private]
Definition at line 17 of file FREngine.h.
Referenced by Cleanup(), Init(), and Load().
The documentation for this class was generated from the following files:
Code/Render/Fonts/FREngine.h
Code/Render/Fonts/FREngine.cpp