Virtus: GRenderer Class Reference
GRenderer Class Reference
The core renderer class - Singleton.
#include <GRender.h>
Public Member Functions
~GRenderer ()
bool initialize (unsigned int w, unsigned int h, const char *renderAPI)
void uninitialize ()
void update (float seconds)
void renderScene (int wx, int wy)
GraphicsAPI * getGraphicsAPI ()
GRenderLayer * getLayer (int ID)
GSpriteLayer * getSpriteLayer ()
InterfaceLayer * getInterfaceManager ()
ThreeDRenderLayer * get3DLayer ()
TextureMonitor * getTextureMonitor ()
LogWriter * getRenderLog ()
RenderWindow * getWindow ()
void setRenderWireframeValue (bool value)
bool getRenderWireframeValue ()
Static Public Member Functions
static GRenderer * getRenderer ()
Private Member Functions
void setLayer (int ID, GRenderLayer *Layer)
GRenderer ()
void begin (int wx, int wy)
void end (int wx, int wy)
Private Attributes
GraphicsAPI * m_renderAPI
GRenderLayer * m_renderLayers [Layers_Max]
LogWriter * m_gameRenderLog
TextureMonitor * m_textureMonitor
bool m_shouldRenderWireframe
Static Private Attributes
static const char * TAG = "Renderer"
Detailed Description
The core renderer class - Singleton.
Definition at line 20 of file GRender.h.
Constructor & Destructor Documentation
GRenderer::GRenderer () [private]
Definition at line 11 of file GRender.cpp.
References Layers_Max, m_gameRenderLog, m_renderAPI, m_renderLayers, and m_textureMonitor.
Referenced by getRenderer().
GRenderer::~GRenderer ()
Definition at line 22 of file GRender.cpp.
References uninitialize().
Member Function Documentation
void GRenderer::begin (int wx, int wy) [private]
Definition at line 146 of file GRender.cpp.
References GraphicsAPI::clearScreen(), getGraphicsAPI(), RenderWindow::getHeight(), GraphicsAPI::getRenderWindow(), RenderWindow::getWidth(), getWindow(), m_renderAPI, GraphicsAPI::setupViewport(), and RenderWindow::update().
Referenced by renderScene().
void GRenderer::end (int wx, int wy) [private]
Definition at line 194 of file GRender.cpp.
References GraphicsAPI::clearErrors(), RenderWindow::finalFrame(), getWindow(), and m_renderAPI.
Referenced by renderScene().
ThreeDRenderLayer* GRenderer::get3DLayer () [inline]
Definition at line 80 of file GRender.h.
References Layer_3D, and m_renderLayers.
Referenced by ModelViewer::onLoad().
GraphicsAPI* GRenderer::getGraphicsAPI () [inline]
Definition at line 57 of file GRender.h.
References m_renderAPI.
Referenced by begin(), InterfaceLayer::draw(), Checkbox::draw(), Button::draw(), WorldNode::draw(), TestNode::draw(), TerrainNode::draw(), Plane::draw(), ThreeDRenderLayer::draw(), ViewerUserInterface::draw(), TextureMonitor::f_loadEntity(), FontMap::FontMap(), TerrainPatch::generateDrawLOD(), InterfaceLayer::InterfaceLayer(), FREngine::LoadFontmap(), Plane::Plane(), Camera::renderMoveTo(), TerrainNode::TerrainNode(), TestNode::TestNode(), and WorldNode::WorldNode().
InterfaceLayer* GRenderer::getInterfaceManager () [inline]
Definition at line 75 of file GRender.h.
References Layer_Interface, and m_renderLayers.
Referenced by GEngine::initialize(), ModelViewer::onLoad(), and ModelViewer::onUnload().
GRenderLayer* GRenderer::getLayer (int ID) [inline]
Definition at line 63 of file GRender.h.
References Layers_Max, Layers_Start, and m_renderLayers.
Referenced by TerrainNode::draw(), ModelViewer::onLoad(), ModelViewer::onUnload(), renderScene(), and ModelViewer::updateApplication().
GRenderer * GRenderer::getRenderer () [static]
Definition at line 28 of file GRender.cpp.
References GRenderer(), and renderInstance.
Referenced by FREngine::Cleanup(), FontMap::Cleanup(), GEngine::doFrameUpdate(), InterfaceLayer::draw(), Checkbox::draw(), Button::draw(), WorldNode::draw(), TestNode::draw(), TerrainNode::draw(), Plane::draw(), ThreeDRenderLayer::draw(), ViewerUserInterface::draw(), TextureMonitor::f_loadEntity(), FontMap::FontMap(), GEngine::gameLoop(), TerrainPatch::generateDrawLOD(), GLShader::GLShader(), FREngine::Init(), GL2GraphicsAPI::initialize(), GEngine::initialize(), InterfaceLayer::InterfaceLayer(), FREngine::Load(), FREngine::LoadFontmap(), GLShader::loadShader(), GLTexture::loadTextureData(), main(), ModelViewer::onLoad(), ModelViewer::onUnload(), Plane::Plane(), GEngine::processEvent(), Camera::renderMoveTo(), TerrainNode::TerrainNode(), TestNode::TestNode(), toggleWireframeFn(), ToggleWireframeHandler::triggerCallback(), ModelViewer::updateApplication(), WorldNode::WorldNode(), GLShader::~GLShader(), TerrainNode::~TerrainNode(), TestNode::~TestNode(), and WorldNode::~WorldNode().
LogWriter* GRenderer::getRenderLog () [inline]
Definition at line 90 of file GRender.h.
References m_gameRenderLog.
Referenced by FREngine::Cleanup(), FontMap::Cleanup(), TextureMonitor::f_loadEntity(), GLShader::GLShader(), FREngine::Init(), GL2GraphicsAPI::initialize(), FREngine::Load(), GLShader::loadShader(), GLTexture::loadTextureData(), and GLShader::~GLShader().
bool GRenderer::getRenderWireframeValue ()
Definition at line 156 of file GRender.cpp.
References m_shouldRenderWireframe.
Referenced by ThreeDRenderLayer::draw(), and ToggleWireframeHandler::triggerCallback().
GSpriteLayer* GRenderer::getSpriteLayer () [inline]
Definition at line 70 of file GRender.h.
References Layer_Sprites, and m_renderLayers.
TextureMonitor* GRenderer::getTextureMonitor () [inline]
Definition at line 85 of file GRender.h.
References m_textureMonitor.
Referenced by InterfaceLayer::InterfaceLayer(), TerrainNode::TerrainNode(), TestNode::TestNode(), WorldNode::WorldNode(), TerrainNode::~TerrainNode(), TestNode::~TestNode(), and WorldNode::~WorldNode().
RenderWindow* GRenderer::getWindow () [inline]
Definition at line 95 of file GRender.h.
References GraphicsAPI::getRenderWindow(), and m_renderAPI.
Referenced by begin(), end(), GEngine::initialize(), and GEngine::processEvent().
bool GRenderer::initialize (unsigned int w, unsigned int h, const char * renderAPI)
Definition at line 38 of file GRender.cpp.
References RenderWindow::create(), GraphicsAPI::getAPIInstance(), GraphicsAPI::getAPISummary(), LogWriter::getPathToLogFile(), GraphicsAPI::getRenderWindow(), GraphicsAPI::initialize(), Layer_3D, Layer_Interface, m_gameRenderLog, m_renderAPI, m_shouldRenderWireframe, m_textureMonitor, setLayer(), TAG, uninitialize(), and LogWriter::writeLine().
void GRenderer::renderScene (int wx, int wy)
Definition at line 169 of file GRender.cpp.
References begin(), GraphicsAPI::clearActiveTexture(), GraphicsAPI::disableBlending(), GRenderLayer::draw(), GraphicsAPI::enableBlending(), end(), getLayer(), Layer_3D, Layer_Interface, m_renderAPI, and GraphicsAPI::setupFor2D().
Referenced by GEngine::gameLoop().
void GRenderer::setLayer (int ID, GRenderLayer * Layer) [inline, private]
Definition at line 33 of file GRender.h.
References Layers_Max, Layers_Start, and m_renderLayers.
Referenced by initialize().
void GRenderer::setRenderWireframeValue (bool value)
Definition at line 162 of file GRender.cpp.
References m_shouldRenderWireframe.
Referenced by toggleWireframeFn(), and ToggleWireframeHandler::triggerCallback().
void GRenderer::uninitialize ()
Definition at line 106 of file GRender.cpp.
References Layers_Max, m_gameRenderLog, m_renderAPI, m_renderLayers, and m_textureMonitor.
Referenced by initialize(), and ~GRenderer().
void GRenderer::update (float seconds)
Definition at line 210 of file GRender.cpp.
References Layers_Max, m_renderLayers, and GRenderLayer::update().
Referenced by GEngine::doFrameUpdate().
Member Data Documentation
LogWriter* GRenderer::m_gameRenderLog [private]
Definition at line 28 of file GRender.h.
Referenced by getRenderLog(), GRenderer(), initialize(), and uninitialize().
GraphicsAPI* GRenderer::m_renderAPI [private]
Definition at line 25 of file GRender.h.
Referenced by begin(), end(), getGraphicsAPI(), getWindow(), GRenderer(), initialize(), renderScene(), and uninitialize().
GRenderLayer* GRenderer::m_renderLayers[Layers_Max] [private]
Definition at line 27 of file GRender.h.
Referenced by get3DLayer(), getInterfaceManager(), getLayer(), getSpriteLayer(), GRenderer(), setLayer(), uninitialize(), and update().
bool GRenderer::m_shouldRenderWireframe [private]
Definition at line 31 of file GRender.h.
Referenced by getRenderWireframeValue(), initialize(), and setRenderWireframeValue().
TextureMonitor* GRenderer::m_textureMonitor [private]
Definition at line 30 of file GRender.h.
Referenced by getTextureMonitor(), GRenderer(), initialize(), and uninitialize().
const char * GRenderer::TAG = "Renderer" [static, private]
Definition at line 23 of file GRender.h.
Referenced by initialize().
The documentation for this class was generated from the following files:
Code/Render/GRender.h
Code/Render/GRender.cpp