Virtus: LocalDataOutputStream Class Reference
LocalDataOutputStream Class Reference
#include <LocalOutputStream.h>
Public Member Functions
LocalDataOutputStream (const char *FilePath)
~LocalDataOutputStream ()
bool isOpen ()
bool open (bool textMode)
void close ()
bool write (const void *Data, unsigned long len)
void flush ()
Private Attributes
char * m_filePath
FILE * m_fileOutputStream
Detailed Description
Definition at line 7 of file LocalOutputStream.h.
Constructor & Destructor Documentation
LocalDataOutputStream::LocalDataOutputStream (const char * FilePath)
Definition at line 3 of file LocalOutputStream.cpp.
References m_fileOutputStream, and m_filePath.
LocalDataOutputStream::~LocalDataOutputStream ()
Definition at line 14 of file LocalOutputStream.cpp.
References close(), isOpen(), and m_filePath.
Member Function Documentation
void LocalDataOutputStream::close () [virtual]
Implements DataOutputStream.
Definition at line 86 of file LocalOutputStream.cpp.
References isOpen(), and m_fileOutputStream.
Referenced by ~LocalDataOutputStream().
void LocalDataOutputStream::flush () [virtual]
Implements DataOutputStream.
Definition at line 123 of file LocalOutputStream.cpp.
References isOpen(), and m_fileOutputStream.
bool LocalDataOutputStream::isOpen () [virtual]
Implements DataOutputStream.
Definition at line 38 of file LocalOutputStream.cpp.
References m_fileOutputStream.
Referenced by close(), flush(), open(), write(), and ~LocalDataOutputStream().
bool LocalDataOutputStream::open (bool textMode) [virtual]
Implements DataOutputStream.
Definition at line 54 of file LocalOutputStream.cpp.
References isOpen(), m_fileOutputStream, and m_filePath.
bool LocalDataOutputStream::write (const void * Data, unsigned long len) [virtual]
Implements DataOutputStream.
Definition at line 100 of file LocalOutputStream.cpp.
References isOpen(), and m_fileOutputStream.
Member Data Documentation
FILE* LocalDataOutputStream::m_fileOutputStream [private]
Definition at line 12 of file LocalOutputStream.h.
Referenced by close(), flush(), isOpen(), LocalDataOutputStream(), open(), and write().
char* LocalDataOutputStream::m_filePath [private]
Definition at line 11 of file LocalOutputStream.h.
Referenced by LocalDataOutputStream(), open(), and ~LocalDataOutputStream().
The documentation for this class was generated from the following files:
Code/Filesystem/LocalOutputStream.h
Code/Filesystem/LocalOutputStream.cpp