Virtus: TerrainNode Class Reference
TerrainNode Class Reference
#include <TerrainNode.h>
Public Member Functions
TerrainNode ()
~TerrainNode ()
void update (float seconds)
void draw (Camera *cam)
Private Member Functions
void recalculateLightMaps ()
void recalculateTerrainCoordinates ()
float getBrightnessAtPoint (unsigned int x, unsigned int z)
void terrainCrossProduct (unsigned int x1, unsigned int z1, unsigned int x2, unsigned int z2, unsigned int x3, unsigned int z3, float *auxNormal)
void terrainNormalize (float *v)
void terrainAddVector (float *v, float *o)
Private Attributes
unsigned int m_patchSize
unsigned int m_numPatches
TerrainPatch ** m_patches
float scaleFactorX
float scaleFactorY
float scaleFactorZ
float m_ambientLight
Shader * m_terrainShader
float * m_lightingData
float * m_normalData
bool m_lightmapDirty
TerrainData * m_terrainDataCl
Texture * m_terrainTextureData
Texture * m_terrainLightMap
Detailed Description
Definition at line 17 of file TerrainNode.h.
Constructor & Destructor Documentation
TerrainNode::TerrainNode ()
Definition at line 14 of file TerrainNode.cpp.
References Filesystem::evaluateChild(), TerrainData::generateUsingSineFaultAlgorythm(), GRenderer::getGraphicsAPI(), TerrainData::getLightmapData(), TerrainData::getNormalData(), GRenderer::getRenderer(), Filesystem::getRoot(), GraphicsAPI::getShaderFactory(), TerrainData::getTerrainData(), TerrainData::getTerrainLength(), TextureMonitor::getTexture(), GRenderer::getTextureMonitor(), TerrainData::getUVData(), ShaderFactory::loadShader(), m_ambientLight, m_lightingData, m_lightmapDirty, m_normalData, m_numPatches, m_patches, m_patchSize, m_terrainDataCl, m_terrainLightMap, m_terrainShader, m_terrainTextureData, GraphicsAPI::newTexture(), scaleFactorX, scaleFactorY, scaleFactorZ, Shader::setNumberOfTextures(), Shader::setTextureName(), and verticesPerPatch.
TerrainNode::~TerrainNode ()
Definition at line 100 of file TerrainNode.cpp.
References GRenderer::getRenderer(), GRenderer::getTextureMonitor(), m_terrainDataCl, m_terrainLightMap, m_terrainTextureData, and TextureMonitor::releaseTexture().
Member Function Documentation
void TerrainNode::draw (Camera * cam) [virtual]
Reimplemented from SceneNode.
Definition at line 297 of file TerrainNode.cpp.
References Shader::activateShader(), Shader::deactivateShader(), ThreeDRenderLayer::getActiveCamera(), GRenderer::getGraphicsAPI(), GRenderer::getLayer(), Camera::getPosition(), GRenderer::getRenderer(), Vector3f::getX(), Vector3f::getY(), Vector3f::getZ(), Layer_3D, m_lightmapDirty, m_numPatches, m_patches, m_patchSize, SceneNode::m_position, SceneNode::m_rotation, m_terrainLightMap, m_terrainShader, m_terrainTextureData, GraphicsAPI::popMatrix(), GraphicsAPI::pushMatrix(), recalculateLightMaps(), GraphicsAPI::rotateMatrix(), scaleFactorX, scaleFactorY, scaleFactorZ, Shader::setTexture(), and GraphicsAPI::translateMatrix().
float TerrainNode::getBrightnessAtPoint (unsigned int x, unsigned int z) [private]
Definition at line 155 of file TerrainNode.cpp.
References TerrainData::getTerrainLength(), m_lightingData, and m_terrainDataCl.
void TerrainNode::recalculateLightMaps () [private]
Definition at line 167 of file TerrainNode.cpp.
References TerrainData::getTerrainData(), TerrainData::getTerrainLength(), Vector3f::getX(), Vector3f::getZ(), heightBasedLightmap, input_data_float_luminance, Texture::loadTextureData(), m_ambientLight, m_lightingData, m_terrainDataCl, m_terrainLightMap, Vector3f::normalize(), positionalLighting, Vector3f::setX(), Vector3f::setY(), Vector3f::setZ(), and slopeLighting.
Referenced by draw().
void TerrainNode::recalculateTerrainCoordinates () [private]
void TerrainNode::terrainAddVector (float * v, float * o) [private]
Definition at line 110 of file TerrainNode.cpp.
void TerrainNode::terrainCrossProduct (unsigned int x1, unsigned int z1, unsigned int x2, unsigned int z2, unsigned int x3, unsigned int z3, float * auxNormal) [private]
Definition at line 128 of file TerrainNode.cpp.
References TerrainData::getTerrainData(), TerrainData::getTerrainLength(), and m_terrainDataCl.
void TerrainNode::terrainNormalize (float * v) [private]
Definition at line 117 of file TerrainNode.cpp.
void TerrainNode::update (float seconds) [virtual]
Reimplemented from SceneNode.
Definition at line 163 of file TerrainNode.cpp.
Member Data Documentation
float TerrainNode::m_ambientLight [private]
Definition at line 29 of file TerrainNode.h.
Referenced by recalculateLightMaps(), and TerrainNode().
float* TerrainNode::m_lightingData [private]
Definition at line 32 of file TerrainNode.h.
Referenced by getBrightnessAtPoint(), recalculateLightMaps(), and TerrainNode().
bool TerrainNode::m_lightmapDirty [private]
Definition at line 35 of file TerrainNode.h.
Referenced by draw(), and TerrainNode().
float* TerrainNode::m_normalData [private]
Definition at line 33 of file TerrainNode.h.
Referenced by TerrainNode().
unsigned int TerrainNode::m_numPatches [private]
Definition at line 22 of file TerrainNode.h.
Referenced by draw(), and TerrainNode().
TerrainPatch** TerrainNode::m_patches [private]
Definition at line 23 of file TerrainNode.h.
Referenced by draw(), and TerrainNode().
unsigned int TerrainNode::m_patchSize [private]
Definition at line 21 of file TerrainNode.h.
Referenced by draw(), and TerrainNode().
TerrainData* TerrainNode::m_terrainDataCl [private]
Definition at line 37 of file TerrainNode.h.
Referenced by getBrightnessAtPoint(), recalculateLightMaps(), terrainCrossProduct(), TerrainNode(), and ~TerrainNode().
Texture* TerrainNode::m_terrainLightMap [private]
Definition at line 40 of file TerrainNode.h.
Referenced by draw(), recalculateLightMaps(), TerrainNode(), and ~TerrainNode().
Shader* TerrainNode::m_terrainShader [private]
Definition at line 31 of file TerrainNode.h.
Referenced by draw(), and TerrainNode().
Texture* TerrainNode::m_terrainTextureData [private]
Definition at line 39 of file TerrainNode.h.
Referenced by draw(), TerrainNode(), and ~TerrainNode().
float TerrainNode::scaleFactorX [private]
Definition at line 25 of file TerrainNode.h.
Referenced by draw(), and TerrainNode().
float TerrainNode::scaleFactorY [private]
Definition at line 26 of file TerrainNode.h.
Referenced by draw(), and TerrainNode().
float TerrainNode::scaleFactorZ [private]
Definition at line 27 of file TerrainNode.h.
Referenced by draw(), and TerrainNode().
The documentation for this class was generated from the following files:
Code/Render/3D/Terrain/TerrainNode.h
Code/Render/3D/Terrain/TerrainNode.cpp