Virtus: WorkerBee Class Reference
WorkerBee Class Reference
Implementation of a thread that takes and processes job from a hive and processes it.
#include <Bee.h>
Public Member Functions
WorkerBee (int number)
~WorkerBee ()
void run (void *Arg)
Entry point overloaded from the base Thread class, this is the first function to be run.
void hiveUpdate ()
int getBeeStatus ()
Private Attributes
BeeHive * m_hive
int m_beeNumber
int m_beeStatus
Mutex beeStatusAccessMutex
Detailed Description
Implementation of a thread that takes and processes job from a hive and processes it.
Definition at line 16 of file Bee.h.
Constructor & Destructor Documentation
WorkerBee::WorkerBee (int number)
Definition at line 6 of file Bee.cpp.
References beeStatusAccessMutex, Mutex::Lock(), m_beeNumber, m_beeStatus, and Mutex::Unlock().
WorkerBee::~WorkerBee ()
Definition at line 18 of file Bee.cpp.
Member Function Documentation
int WorkerBee::getBeeStatus ()
Definition at line 63 of file Bee.cpp.
References beeStatusAccessMutex, Mutex::Lock(), m_beeStatus, and Mutex::Unlock().
void WorkerBee::hiveUpdate ()
void WorkerBee::run (void * Arg) [virtual]
Entry point overloaded from the base Thread class, this is the first function to be run.
Implements Thread.
Definition at line 23 of file Bee.cpp.
References BeeHive::beeRequestNextJob(), beeStatusAccessMutex, WorkerJob::getErrorDetails(), WorkerJob::getStatus(), Mutex::Lock(), m_beeNumber, m_beeStatus, m_hive, WorkerJob::processJob(), and Mutex::Unlock().
Member Data Documentation
Mutex WorkerBee::beeStatusAccessMutex [private]
Definition at line 25 of file Bee.h.
Referenced by getBeeStatus(), run(), and WorkerBee().
int WorkerBee::m_beeNumber [private]
Definition at line 22 of file Bee.h.
Referenced by run(), and WorkerBee().
int WorkerBee::m_beeStatus [private]
Definition at line 24 of file Bee.h.
Referenced by getBeeStatus(), run(), and WorkerBee().
BeeHive* WorkerBee::m_hive [private]
Definition at line 19 of file Bee.h.
Referenced by run().
The documentation for this class was generated from the following files:
Code/HIVE/Bee.h
Code/HIVE/Bee.cpp