Virtus: WorldNode Class Reference
WorldNode Class Reference
#include <WorldNode.h>
Public Member Functions
WorldNode (const char *SkydomeFile, float r)
~WorldNode ()
void update (float seconds)
void draw (Camera *cam)
Private Member Functions
void f_calculateVertices ()
Private Attributes
VertexSet * m_skydomeVSet
Texture * m_panoramicDomeTexture
float m_radius
Detailed Description
Definition at line 7 of file WorldNode.h.
Constructor & Destructor Documentation
WorldNode::WorldNode (const char * SkydomeFile, float r)
Definition at line 69 of file WorldNode.cpp.
References f_calculateVertices(), GRenderer::getGraphicsAPI(), GRenderer::getRenderer(), TextureMonitor::getTexture(), GRenderer::getTextureMonitor(), m_panoramicDomeTexture, m_radius, m_skydomeVSet, and GraphicsAPI::newVertexSet().
WorldNode::~WorldNode ()
Definition at line 83 of file WorldNode.cpp.
References GRenderer::getRenderer(), GRenderer::getTextureMonitor(), m_panoramicDomeTexture, m_skydomeVSet, and TextureMonitor::releaseTexture().
Member Function Documentation
void WorldNode::draw (Camera * cam) [virtual]
Reimplemented from SceneNode.
Definition at line 133 of file WorldNode.cpp.
References VertexSet::Draw(), GRenderer::getGraphicsAPI(), Vector3f::getMatrix(), Camera::getPosition(), GRenderer::getRenderer(), Camera::getRotation(), m_panoramicDomeTexture, m_skydomeVSet, Texture::makeActive(), phi_stride, GraphicsAPI::popMatrix(), GraphicsAPI::pushMatrix(), QUADS, GraphicsAPI::resetMatrix(), GraphicsAPI::rotateMatrix(), GraphicsAPI::setDepthTesting(), theta_stride, and GraphicsAPI::translateMatrix().
void WorldNode::f_calculateVertices () [private]
Definition at line 90 of file WorldNode.cpp.
References addToUV(), addToVertices(), m_radius, m_skydomeVSet, phi_stride, VertexSet::setTextureCoordinates(), VertexSet::setVertices(), and theta_stride.
Referenced by WorldNode().
void WorldNode::update (float seconds) [virtual]
Reimplemented from SceneNode.
Definition at line 128 of file WorldNode.cpp.
Member Data Documentation
Texture* WorldNode::m_panoramicDomeTexture [private]
Definition at line 13 of file WorldNode.h.
Referenced by draw(), WorldNode(), and ~WorldNode().
float WorldNode::m_radius [private]
Definition at line 15 of file WorldNode.h.
Referenced by f_calculateVertices(), and WorldNode().
VertexSet* WorldNode::m_skydomeVSet [private]
Definition at line 12 of file WorldNode.h.
Referenced by draw(), f_calculateVertices(), WorldNode(), and ~WorldNode().
The documentation for this class was generated from the following files:
Code/Render/3D/WorldNode.h
Code/Render/3D/WorldNode.cpp