Virtus: File Class Reference
File Class Reference
The abstraction of a file within the filesystem.
#include <File.h>
Public Member Functions
int getType ()
virtual ~File ()
virtual DataInputStream * createInputStream ()=0
Create a input stream to that file.
virtual DataOutputStream * createOutputStream ()=0
Create a output stream to that file.
virtual bool exists ()=0
Returns true if the file actually exists, or will be created when a output stream is found.
virtual unsigned long length ()=0
Return the length of the file.
Detailed Description
The abstraction of a file within the filesystem.
Definition at line 13 of file File.h.
Constructor & Destructor Documentation
virtual File::~File () [inline, virtual]
Definition at line 24 of file File.h.
Member Function Documentation
virtual DataInputStream* File::createInputStream () [pure virtual]
Create a input stream to that file.
Implemented in LocalFile.
Referenced by TextureMonitor::f_loadEntity(), Filesystem::getFileInputStream(), FREngine::Load(), ConfigurationInstance::loadFromPath(), and GLShaderFactory::loadShader().
virtual DataOutputStream* File::createOutputStream () [pure virtual]
Create a output stream to that file.
Implemented in LocalFile.
Referenced by Filesystem::getFileOutputStream(), LogWriter::LogWriter(), and ConfigurationInstance::writeToPath().
virtual bool File::exists () [pure virtual]
Returns true if the file actually exists, or will be created when a output stream is found.
Implemented in LocalFile.
int File::getType () [inline, virtual]
Implements FilesystemNode.
Definition at line 19 of file File.h.
References fileId.
Referenced by FREngine::Load(), and GLShaderFactory::loadShader().
virtual unsigned long File::length () [pure virtual]
Return the length of the file.
Implemented in LocalFile.
Referenced by FREngine::Load(), and GLShaderFactory::loadShader().
The documentation for this class was generated from the following file:
Code/Filesystem/File.h