Virtus: RenderLog Class Reference
RenderLog Class Reference
#include <RenderLog.h>
Public Member Functions
RenderLog (const char *outputFile)
~RenderLog ()
void writeToLogFile (const char *line)
Private Attributes
FILE * m_logfileHandle
Detailed Description
Definition at line 5 of file RenderLog.h.
Constructor & Destructor Documentation
RenderLog::RenderLog (const char * outputFile)
Definition at line 13 of file RenderLog.cpp.
References m_logfileHandle, and writeToLogFile().
RenderLog::~RenderLog ()
Definition at line 39 of file RenderLog.cpp.
References m_logfileHandle.
Member Function Documentation
void RenderLog::writeToLogFile (const char * line)
Definition at line 4 of file RenderLog.cpp.
References m_logfileHandle.
Referenced by FREngine::Cleanup(), FontMap::Cleanup(), TextureMonitor::f_loadEntity(), GLShader::GLShader(), FREngine::Init(), GRenderer::initialize(), GL2GraphicsAPI::initialize(), FREngine::Load(), GLShader::loadShader(), GLTexture::loadTextureData(), RenderLog(), and GLShader::~GLShader().
Member Data Documentation
FILE* RenderLog::m_logfileHandle [private]
Definition at line 8 of file RenderLog.h.
Referenced by RenderLog(), writeToLogFile(), and ~RenderLog().
The documentation for this class was generated from the following files:
Code/Render/RenderLog.h
Code/Render/RenderLog.cpp