Virtus: TextureMonitor Class Reference
TextureMonitor Class Reference
#include <TextureMonitor.h>
Public Member Functions
TextureMonitor ()
~TextureMonitor ()
Texture * getTexture (const char *Filename)
void releaseTexture (Texture *texture)
Private Member Functions
void f_freeEntity (void *m_Entity)
void * f_loadEntity (std::string Name)
Private Attributes
TextureLoader m_Loader
Static Private Attributes
static const char * TAG = "TextureMonitor"
Detailed Description
Definition at line 11 of file TextureMonitor.h.
Constructor & Destructor Documentation
TextureMonitor::TextureMonitor ()
Definition at line 6 of file TextureMonitor.cpp.
TextureMonitor::~TextureMonitor ()
Definition at line 10 of file TextureMonitor.cpp.
References f_freeEntity(), and ResourceMonitor::m_resourceList.
Member Function Documentation
void TextureMonitor::f_freeEntity (void * m_Entity) [private, virtual]
Reimplemented from ResourceMonitor.
Definition at line 20 of file TextureMonitor.cpp.
Referenced by ~TextureMonitor().
void * TextureMonitor::f_loadEntity (std::string Name) [private, virtual]
Reimplemented from ResourceMonitor.
Definition at line 27 of file TextureMonitor.cpp.
References File::createInputStream(), Filesystem::evaluateChild(), ResourceMonitor::f_addEntity(), fileId, GRenderer::getGraphicsAPI(), GRenderer::getRenderer(), GRenderer::getRenderLog(), Filesystem::getRoot(), FilesystemNode::getType(), TextureLoader::load(), m_Loader, GraphicsAPI::newTexture(), DataInputStream::open(), TAG, and LogWriter::writeLine().
Texture * TextureMonitor::getTexture (const char * Filename)
Definition at line 90 of file TextureMonitor.cpp.
References ResourceMonitor::rmGetResource().
Referenced by InterfaceLayer::InterfaceLayer(), TerrainNode::TerrainNode(), TestNode::TestNode(), and WorldNode::WorldNode().
void TextureMonitor::releaseTexture (Texture * texture)
Definition at line 94 of file TextureMonitor.cpp.
References ResourceMonitor::rmReleaseResource().
Referenced by TerrainNode::~TerrainNode(), TestNode::~TestNode(), and WorldNode::~WorldNode().
Member Data Documentation
TextureLoader TextureMonitor::m_Loader [private]
Definition at line 14 of file TextureMonitor.h.
Referenced by f_loadEntity().
const char * TextureMonitor::TAG = "TextureMonitor" [static, private]
Definition at line 16 of file TextureMonitor.h.
Referenced by f_loadEntity().
The documentation for this class was generated from the following files:
Code/Render/TextureMonitor/TextureMonitor.h
Code/Render/TextureMonitor/TextureMonitor.cpp