Virtus: SceneNode Class Reference
SceneNode Class Reference
#include <SceneNode.h>
Public Member Functions
SceneNode ()
virtual ~SceneNode ()
void addChildNode (SceneNode *node)
void removeChildNode (SceneNode *node)
virtual void update (float seconds)
virtual void draw (Camera *cam)
unsigned int numChildren ()
SceneNode * getChild (unsigned int i)
point3f_t * getPosition ()
point3f_t * getRotation ()
Protected Attributes
point3f_t m_position
point3f_t m_rotation
std::vector< SceneNode * > m_childNodes
Detailed Description
Definition at line 7 of file SceneNode.h.
Constructor & Destructor Documentation
SceneNode::SceneNode () [inline]
Definition at line 22 of file SceneNode.h.
virtual SceneNode::~SceneNode () [inline, virtual]
Definition at line 26 of file SceneNode.h.
References m_childNodes, and numChildren().
Member Function Documentation
void SceneNode::addChildNode (SceneNode * node) [inline]
Definition at line 41 of file SceneNode.h.
References m_childNodes.
Referenced by ModelViewer::onLoad().
virtual void SceneNode::draw (Camera * cam) [inline, virtual]
Reimplemented in Plane, TerrainNode, TestNode, VoxelObject, and WorldNode.
Definition at line 75 of file SceneNode.h.
References m_childNodes, and numChildren().
Referenced by ThreeDRenderLayer::draw().
SceneNode* SceneNode::getChild (unsigned int i) [inline]
Definition at line 90 of file SceneNode.h.
References m_childNodes.
point3f_t* SceneNode::getPosition () [inline]
Definition at line 95 of file SceneNode.h.
References m_position.
Referenced by ModelViewer::onLoad().
point3f_t* SceneNode::getRotation () [inline]
Definition at line 100 of file SceneNode.h.
References m_rotation.
unsigned int SceneNode::numChildren () [inline]
Definition at line 85 of file SceneNode.h.
References m_childNodes.
Referenced by draw(), removeChildNode(), update(), and ~SceneNode().
void SceneNode::removeChildNode (SceneNode * node) [inline]
Definition at line 46 of file SceneNode.h.
References m_childNodes, and numChildren().
virtual void SceneNode::update (float seconds) [inline, virtual]
Reimplemented in TerrainNode, TestNode, and WorldNode.
Definition at line 64 of file SceneNode.h.
References m_childNodes, and numChildren().
Referenced by ThreeDRenderLayer::update().
Member Data Documentation
std::vector<SceneNode*> SceneNode::m_childNodes [protected]
Definition at line 18 of file SceneNode.h.
Referenced by addChildNode(), draw(), getChild(), numChildren(), removeChildNode(), update(), and ~SceneNode().
point3f_t SceneNode::m_position [protected]
Definition at line 12 of file SceneNode.h.
Referenced by TestNode::draw(), TerrainNode::draw(), and getPosition().
point3f_t SceneNode::m_rotation [protected]
Definition at line 15 of file SceneNode.h.
Referenced by TestNode::draw(), TerrainNode::draw(), and getRotation().
The documentation for this class was generated from the following file:
Code/Render/3D/SceneNode.h