Virtus: ConfigurationReader Class Reference
ConfigurationReader Class Reference
#include <ConfigurationReader.h>
Static Public Member Functions
static ConfigurationNode * getNextNode (DataInputStream *node)
Static Private Member Functions
static void skipWhitespace (DataInputStream *node)
static bool getString (DataInputStream *node, char *outputBuffer, unsigned int mlen)
static bool getNextWord (DataInputStream *node, char *OutputBuffer, unsigned int mlen)
static ConfigurationNode * readFolderNode (DataInputStream *node)
static ConfigurationNode * readStringNode (DataInputStream *node)
static ConfigurationNode * readNumberNode (DataInputStream *node)
Detailed Description
Definition at line 6 of file ConfigurationReader.h.
Member Function Documentation
ConfigurationNode * ConfigurationReader::getNextNode (DataInputStream * node) [static]
Definition at line 404 of file ConfigurationReader.cpp.
References getNextWord(), readFolderNode(), readNumberNode(), and readStringNode().
Referenced by ConfigurationInstance::loadFromPath(), and readFolderNode().
bool ConfigurationReader::getNextWord (DataInputStream * node, char * OutputBuffer, unsigned int mlen) [static, private]
Definition at line 90 of file ConfigurationReader.cpp.
References getString(), DataInputStream::read(), DataInputStream::rewind(), and skipWhitespace().
Referenced by getNextNode(), readFolderNode(), readNumberNode(), and readStringNode().
bool ConfigurationReader::getString (DataInputStream * node, char * outputBuffer, unsigned int mlen) [static, private]
Definition at line 38 of file ConfigurationReader.cpp.
References DataInputStream::read().
Referenced by getNextWord().
ConfigurationNode * ConfigurationReader::readFolderNode (DataInputStream * node) [static, private]
Definition at line 191 of file ConfigurationReader.cpp.
References ConfigurationFolder::addChild(), getNextNode(), and getNextWord().
Referenced by getNextNode().
ConfigurationNode * ConfigurationReader::readNumberNode (DataInputStream * node) [static, private]
Definition at line 322 of file ConfigurationReader.cpp.
References getNextWord().
Referenced by getNextNode().
ConfigurationNode * ConfigurationReader::readStringNode (DataInputStream * node) [static, private]
Definition at line 254 of file ConfigurationReader.cpp.
References getNextWord().
Referenced by getNextNode().
void ConfigurationReader::skipWhitespace (DataInputStream * node) [static, private]
Definition at line 7 of file ConfigurationReader.cpp.
References DataInputStream::read(), and DataInputStream::rewind().
Referenced by getNextWord().
The documentation for this class was generated from the following files:
Code/Configure/ConfigurationReader.h
Code/Configure/ConfigurationReader.cpp