Virtus: LogWriter Class Reference
LogWriter Class Reference
#include <LogWriter.h>
Public Member Functions
LogWriter (File *file)
~LogWriter ()
void writeData (const char *Data)
Static Public Member Functions
static File * getPathToLogFile (const char *Name)
Private Attributes
DataOutputStream * m_logOutStream
Detailed Description
Definition at line 5 of file LogWriter.h.
Constructor & Destructor Documentation
LogWriter::LogWriter (File * file)
Definition at line 5 of file LogWriter.cpp.
References File::createOutputStream(), FilesystemNode::getName(), m_logOutStream, and DataOutputStream::open().
LogWriter::~LogWriter ()
Definition at line 29 of file LogWriter.cpp.
References m_logOutStream.
Member Function Documentation
File * LogWriter::getPathToLogFile (const char * Name) [static]
Definition at line 58 of file LogWriter.cpp.
References Filesystem::evaluateChild(), folderId, Filesystem::getRoot(), Folder::getType(), Folder::newChild(), and Folder::searchForChild().
Referenced by GEngine::initialize().
void LogWriter::writeData (const char * Data)
Definition at line 40 of file LogWriter.cpp.
References DataOutputStream::flush(), DataOutputStream::isOpen(), m_logOutStream, and DataOutputStream::write().
Referenced by BeeHive::BeeHive(), GEngine::initialize(), GEngine::setErrorDetails(), GEngine::uninitialize(), and BeeHive::~BeeHive().
Member Data Documentation
DataOutputStream* LogWriter::m_logOutStream [private]
Definition at line 8 of file LogWriter.h.
Referenced by LogWriter(), writeData(), and ~LogWriter().
The documentation for this class was generated from the following files:
Code/LogWriter/LogWriter.h
Code/LogWriter/LogWriter.cpp