Virtus: FontMap Class Reference
FontMap Class Reference
#include <FontMap.h>
Public Member Functions
FontMap ()
void Render (int Char, float x, float y)
void Render (int Char, float x, float y, float offx, float offy, float w, float h)
void Cleanup ()
FontChar * GetChar (int Char)
Public Attributes
FontChar CharList [255]
int PointSize
VertexSet * drawBuffer
Detailed Description
Definition at line 14 of file FontMap.h.
Constructor & Destructor Documentation
FontMap::FontMap ()
Definition at line 4 of file FontMap.cpp.
References drawBuffer, GRenderer::getGraphicsAPI(), GRenderer::getRenderer(), GraphicsAPI::newVertexSet(), PointSize, VertexSet::setTextureCoordinates(), and VertexSet::setVertices().
Member Function Documentation
void FontMap::Cleanup ()
Definition at line 72 of file FontMap.cpp.
References CharList, FontChar::charTexture, drawBuffer, GRenderer::getRenderer(), GRenderer::getRenderLog(), and RenderLog::writeToLogFile().
FontChar * FontMap::GetChar (int Char)
Definition at line 94 of file FontMap.cpp.
References CharList.
void FontMap::Render (int Char, float x, float y)
Definition at line 27 of file FontMap.cpp.
References CharList, FontChar::OffsetX, and FontChar::OffsetY.
void FontMap::Render (int Char, float x, float y, float offx, float offy, float w, float h)
Definition at line 37 of file FontMap.cpp.
References CharList, FontChar::charTexture, VertexSet::Draw(), drawBuffer, VertexSet::getVertices(), Texture::makeActive(), and QUADS.
Member Data Documentation
FontChar FontMap::CharList[255]
Definition at line 17 of file FontMap.h.
Referenced by Cleanup(), GetChar(), FREngine::LoadFontmap(), and Render().
VertexSet* FontMap::drawBuffer
Definition at line 21 of file FontMap.h.
Referenced by Cleanup(), FontMap(), and Render().
int FontMap::PointSize
Definition at line 19 of file FontMap.h.
Referenced by FontMap(), and FREngine::LoadFontmap().
The documentation for this class was generated from the following files:
Code/Render/Fonts/FontMap.h
Code/Render/Fonts/FontMap.cpp