Virtus: TerrainData Class Reference
TerrainData Class Reference
#include <TerrainData.h>
Public Member Functions
TerrainData (unsigned int l_terrainLength)
~TerrainData ()
float * getTerrainData ()
float * getUVData ()
float * getLightmapData ()
float * getNormalData ()
unsigned int getTerrainLength ()
void generateUsingSineFaultAlgorythm (unsigned int l_numIterations, float distortionStart, float distortionMin, float sineCurveMagnitude)
void recalculateUV ()
Private Attributes
float * m_terrainData
float * m_uvData
float * m_lightmapData
float * m_normalData
unsigned int m_terrainLength
Detailed Description
Definition at line 4 of file TerrainData.h.
Constructor & Destructor Documentation
TerrainData::TerrainData (unsigned int l_terrainLength)
Definition at line 6 of file TerrainData.cpp.
References m_lightmapData, m_normalData, m_terrainData, m_terrainLength, m_uvData, and recalculateUV().
TerrainData::~TerrainData ()
Definition at line 53 of file TerrainData.cpp.
References m_lightmapData, m_normalData, m_terrainData, and m_uvData.
Member Function Documentation
void TerrainData::generateUsingSineFaultAlgorythm (unsigned int l_numIterations, float distortionStart, float distortionMin, float sineCurveMagnitude)
Definition at line 95 of file TerrainData.cpp.
References m_terrainData, and m_terrainLength.
Referenced by TerrainNode::TerrainNode().
float * TerrainData::getLightmapData ()
Definition at line 82 of file TerrainData.cpp.
References m_lightmapData.
Referenced by TerrainNode::TerrainNode().
float * TerrainData::getNormalData ()
Definition at line 89 of file TerrainData.cpp.
References m_normalData.
Referenced by TerrainNode::TerrainNode().
float * TerrainData::getTerrainData ()
Definition at line 69 of file TerrainData.cpp.
References m_terrainData.
Referenced by TerrainNode::recalculateLightMaps(), TerrainNode::terrainCrossProduct(), and TerrainNode::TerrainNode().
unsigned int TerrainData::getTerrainLength () [inline]
Definition at line 26 of file TerrainData.h.
References m_terrainLength.
Referenced by TerrainNode::getBrightnessAtPoint(), TerrainNode::recalculateLightMaps(), TerrainNode::terrainCrossProduct(), and TerrainNode::TerrainNode().
float * TerrainData::getUVData ()
Definition at line 76 of file TerrainData.cpp.
References m_uvData.
Referenced by TerrainNode::TerrainNode().
void TerrainData::recalculateUV ()
Definition at line 178 of file TerrainData.cpp.
References m_terrainLength, and m_uvData.
Referenced by TerrainData().
Member Data Documentation
float* TerrainData::m_lightmapData [private]
Definition at line 10 of file TerrainData.h.
Referenced by getLightmapData(), TerrainData(), and ~TerrainData().
float* TerrainData::m_normalData [private]
Definition at line 11 of file TerrainData.h.
Referenced by getNormalData(), TerrainData(), and ~TerrainData().
float* TerrainData::m_terrainData [private]
Definition at line 8 of file TerrainData.h.
Referenced by generateUsingSineFaultAlgorythm(), getTerrainData(), TerrainData(), and ~TerrainData().
unsigned int TerrainData::m_terrainLength [private]
Definition at line 13 of file TerrainData.h.
Referenced by generateUsingSineFaultAlgorythm(), getTerrainLength(), recalculateUV(), and TerrainData().
float* TerrainData::m_uvData [private]
Definition at line 9 of file TerrainData.h.
Referenced by getUVData(), recalculateUV(), TerrainData(), and ~TerrainData().
The documentation for this class was generated from the following files:
Code/Render/3D/Terrain/TerrainData.h
Code/Render/3D/Terrain/TerrainData.cpp