Virtus: EventManager Class Reference
EventManager Class Reference
Manages and stores mapping between events.
#include <EventManager.h>
Public Member Functions
EventManager ()
~EventManager ()
void setNumberOfEvents (unsigned int number)
Set the number of possible events (From 0 to number)
void unregisterEventCallback (unsigned int event, EventCallback *Callback)
Unregister the specified callback from the event.
void registerEventCallback (unsigned int event, EventCallback *Callback)
Register the specified callback to the event.
void triggerEvent (unsigned int event, std::vector< int > F, int Flags)
Notify the event manager that the specified event has occured.
Private Member Functions
void freeEvents ()
Private Attributes
unsigned int m_numEvents
event_callback_struct * m_eventCallbacks
Detailed Description
Manages and stores mapping between events.
Definition at line 15 of file EventManager.h.
Constructor & Destructor Documentation
EventManager::EventManager ()
Definition at line 4 of file EventManager.cpp.
References m_eventCallbacks, and m_numEvents.
EventManager::~EventManager ()
Definition at line 10 of file EventManager.cpp.
References freeEvents().
Member Function Documentation
void EventManager::freeEvents () [private]
Definition at line 15 of file EventManager.cpp.
References m_eventCallbacks, event_callback_struct::m_eventList, and m_numEvents.
Referenced by setNumberOfEvents(), and ~EventManager().
void EventManager::registerEventCallback (unsigned int event, EventCallback * Callback)
Register the specified callback to the event.
Definition at line 65 of file EventManager.cpp.
References m_eventCallbacks, event_callback_struct::m_eventList, and m_numEvents.
Referenced by ModelViewer::onLoad().
void EventManager::setNumberOfEvents (unsigned int number)
Set the number of possible events (From 0 to number)
Definition at line 37 of file EventManager.cpp.
References freeEvents(), m_eventCallbacks, and m_numEvents.
Referenced by ModelViewer::onLoad().
void EventManager::triggerEvent (unsigned int event, std::vector< int > F, int Flags)
Notify the event manager that the specified event has occured.
Definition at line 73 of file EventManager.cpp.
References m_eventCallbacks, event_callback_struct::m_eventList, and m_numEvents.
Referenced by GEngine::sendEventManagerMessage().
void EventManager::unregisterEventCallback (unsigned int event, EventCallback * Callback)
Unregister the specified callback from the event.
Definition at line 51 of file EventManager.cpp.
References m_eventCallbacks, event_callback_struct::m_eventList, and m_numEvents.
Referenced by ModelViewer::onUnload().
Member Data Documentation
event_callback_struct* EventManager::m_eventCallbacks [private]
Definition at line 19 of file EventManager.h.
Referenced by EventManager(), freeEvents(), registerEventCallback(), setNumberOfEvents(), triggerEvent(), and unregisterEventCallback().
unsigned int EventManager::m_numEvents [private]
Definition at line 18 of file EventManager.h.
Referenced by EventManager(), freeEvents(), registerEventCallback(), setNumberOfEvents(), triggerEvent(), and unregisterEventCallback().
The documentation for this class was generated from the following files:
Code/Logic/Event/EventManager.h
Code/Logic/Event/EventManager.cpp