Virtus: Checkbox Class Reference
Checkbox Class Reference
#include <Checkbox.h>
Public Member Functions
Checkbox (float x, float y, float w, float h, Color m_downClr, Color m_upClr)
~Checkbox ()
void draw (InterfaceLayer *IL)
bool handleInput (Input_Event e)
Protected Attributes
bool m_mouseOver
bool m_mouseDown
bool m_isChecked
Detailed Description
Definition at line 8 of file Checkbox.h.
Constructor & Destructor Documentation
Checkbox::Checkbox (float x, float y, float w, float h, Color m_downClr, Color m_upClr)
Definition at line 6 of file Checkbox.cpp.
References m_isChecked, m_mouseDown, and m_mouseOver.
Checkbox::~Checkbox ()
Definition at line 13 of file Checkbox.cpp.
Member Function Documentation
void Checkbox::draw (InterfaceLayer * IL) [virtual]
Implements IElement.
Definition at line 19 of file Checkbox.cpp.
References GraphicsAPI::disableBlending(), InterfaceLayer::drawQuadWithUIElement(), GraphicsAPI::enableBlending(), GRenderer::getGraphicsAPI(), GRenderer::getRenderer(), IElement::height, m_isChecked, m_mouseOver, IElement::width, IElement::x, and IElement::y.
bool Checkbox::handleInput (Input_Event e) [virtual]
Implements IElement.
Definition at line 48 of file Checkbox.cpp.
References Input_Event::Event_Data, Input_Event::Event_ID, IElement::height, input_event_button_one, m_isChecked, m_mouseDown, m_mouseOver, MOUSE_DOWN, MOUSE_UP, IElement::width, IElement::x, and IElement::y.
Member Data Documentation
bool Checkbox::m_isChecked [protected]
Definition at line 14 of file Checkbox.h.
Referenced by Checkbox(), draw(), and handleInput().
bool Checkbox::m_mouseDown [protected]
Definition at line 13 of file Checkbox.h.
Referenced by Checkbox(), and handleInput().
bool Checkbox::m_mouseOver [protected]
Definition at line 12 of file Checkbox.h.
Referenced by Checkbox(), draw(), and handleInput().
The documentation for this class was generated from the following files:
Code/Render/Interface/Checkbox.h
Code/Render/Interface/Checkbox.cpp