Virtus: Shader Class Reference
Shader Class Reference
#include <Shader.h>
Public Member Functions
Shader ()
virtual ~Shader ()
virtual void activateShader ()=0
virtual void deactivateShader ()=0
virtual void setNumberOfTextures (unsigned int number)=0
virtual void setTextureName (unsigned int i, const char *Name)=0
virtual void setTexture (unsigned int i, Texture *tex)=0
Detailed Description
Definition at line 5 of file Shader.h.
Constructor & Destructor Documentation
Shader::Shader () [inline]
Definition at line 11 of file Shader.h.
virtual Shader::~Shader () [inline, virtual]
Definition at line 12 of file Shader.h.
Member Function Documentation
virtual void Shader::activateShader () [pure virtual]
Implemented in GLShader.
Referenced by TestNode::draw(), and TerrainNode::draw().
virtual void Shader::deactivateShader () [pure virtual]
Implemented in GLShader.
Referenced by TestNode::draw(), and TerrainNode::draw().
virtual void Shader::setNumberOfTextures (unsigned int number) [pure virtual]
Implemented in GLShader.
Referenced by TerrainNode::TerrainNode(), and TestNode::TestNode().
virtual void Shader::setTexture (unsigned int i, Texture * tex) [pure virtual]
Implemented in GLShader.
Referenced by TestNode::draw(), and TerrainNode::draw().
virtual void Shader::setTextureName (unsigned int i, const char * Name) [pure virtual]
Implemented in GLShader.
Referenced by TerrainNode::TerrainNode(), and TestNode::TestNode().
The documentation for this class was generated from the following file:
Code/Render/GraphicsAPI/Shader.h