Virtus: ConfigurationInstance Class Reference
ConfigurationInstance Class Reference
#include <ConfigurationInstance.h>
Public Member Functions
ConfigurationInstance (File *fileToLoad)
~ConfigurationInstance ()
void saveInstance ()
ConfigurationNode * getNode (unsigned int i)
unsigned int getNumberOfNodes ()
ConfigurationNode * getNode (const char *Path)
Private Member Functions
void unloadAndFreeAll ()
void loadFromPath ()
void writeToPath ()
ConfigurationNode * internalSearchNode (const char *Path, ConfigurationNode *cNode)
Private Attributes
std::vector< ConfigurationNode * > m_Nodes
File * m_instanceFile
Detailed Description
Definition at line 7 of file ConfigurationInstance.h.
Constructor & Destructor Documentation
ConfigurationInstance::ConfigurationInstance (File * fileToLoad)
Definition at line 8 of file ConfigurationInstance.cpp.
References loadFromPath(), and m_instanceFile.
ConfigurationInstance::~ConfigurationInstance ()
Definition at line 16 of file ConfigurationInstance.cpp.
References saveInstance(), and unloadAndFreeAll().
Member Function Documentation
ConfigurationNode * ConfigurationInstance::getNode (unsigned int i)
Definition at line 142 of file ConfigurationInstance.cpp.
References m_Nodes.
Referenced by GEngine::initialize(), and internalSearchNode().
ConfigurationNode * ConfigurationInstance::getNode (const char * Path)
Definition at line 279 of file ConfigurationInstance.cpp.
References internalSearchNode().
unsigned int ConfigurationInstance::getNumberOfNodes ()
Definition at line 137 of file ConfigurationInstance.cpp.
References m_Nodes.
Referenced by internalSearchNode().
ConfigurationNode * ConfigurationInstance::internalSearchNode (const char * Path, ConfigurationNode * cNode) [private]
Definition at line 147 of file ConfigurationInstance.cpp.
References configurationFolder, ConfigurationFolder::getChild(), ConfigurationNode::getName(), getNode(), getNumberOfNodes(), ConfigurationNode::getType(), and ConfigurationFolder::numberOfChildren().
Referenced by getNode().
void ConfigurationInstance::loadFromPath () [private]
Definition at line 59 of file ConfigurationInstance.cpp.
References File::createInputStream(), ConfigurationReader::getNextNode(), m_instanceFile, m_Nodes, DataInputStream::open(), and unloadAndFreeAll().
Referenced by ConfigurationInstance().
void ConfigurationInstance::saveInstance ()
Definition at line 132 of file ConfigurationInstance.cpp.
References writeToPath().
Referenced by ~ConfigurationInstance().
void ConfigurationInstance::unloadAndFreeAll () [private]
Definition at line 120 of file ConfigurationInstance.cpp.
References m_Nodes.
Referenced by loadFromPath(), and ~ConfigurationInstance().
void ConfigurationInstance::writeToPath () [private]
Definition at line 24 of file ConfigurationInstance.cpp.
References File::createOutputStream(), m_instanceFile, m_Nodes, DataOutputStream::open(), and ConfigurationWriter::outputNode().
Referenced by saveInstance().
Member Data Documentation
File* ConfigurationInstance::m_instanceFile [private]
Definition at line 15 of file ConfigurationInstance.h.
Referenced by ConfigurationInstance(), loadFromPath(), and writeToPath().
std::vector<ConfigurationNode*> ConfigurationInstance::m_Nodes [private]
Definition at line 11 of file ConfigurationInstance.h.
Referenced by getNode(), getNumberOfNodes(), loadFromPath(), unloadAndFreeAll(), and writeToPath().
The documentation for this class was generated from the following files:
Code/Configure/ConfigurationInstance.h
Code/Configure/ConfigurationInstance.cpp