Virtus: ConfigurationFolder Class Reference
ConfigurationFolder Class Reference
A implementation of a configuration folder, it has a number of children pointers to them and a name.
#include <ConfigurationFolder.h>
Public Member Functions
ConfigurationFolder (const char *Name)
~ConfigurationFolder ()
int getType ()
Return that the node is a configuration node.
void addChild (ConfigurationNode *node)
Add the specified child to this node.
ConfigurationNode * getChild (unsigned int iter)
Return the specified child of the node.
size_t numberOfChildren ()
Return the number of children in this node.
Private Member Functions
void freeChildren ()
Private Attributes
std::vector< ConfigurationNode * > m_childNodes
Detailed Description
A implementation of a configuration folder, it has a number of children pointers to them and a name.
Definition at line 10 of file ConfigurationFolder.h.
Constructor & Destructor Documentation
ConfigurationFolder::ConfigurationFolder (const char * Name)
Definition at line 3 of file ConfigurationFolder.cpp.
ConfigurationFolder::~ConfigurationFolder ()
Definition at line 7 of file ConfigurationFolder.cpp.
References freeChildren().
Member Function Documentation
void ConfigurationFolder::addChild (ConfigurationNode * node)
Add the specified child to this node.
Definition at line 12 of file ConfigurationFolder.cpp.
References m_childNodes.
Referenced by ConfigurationReader::readFolderNode().
void ConfigurationFolder::freeChildren () [private]
Definition at line 19 of file ConfigurationFolder.cpp.
References m_childNodes.
Referenced by ~ConfigurationFolder().
ConfigurationNode* ConfigurationFolder::getChild (unsigned int iter) [inline]
Return the specified child of the node.
Definition at line 40 of file ConfigurationFolder.h.
References m_childNodes.
Referenced by ConfigurationInstance::internalSearchNode(), and ConfigurationWriter::outputNode().
int ConfigurationFolder::getType () [inline, virtual]
Return that the node is a configuration node.
Reimplemented from ConfigurationNode.
Definition at line 28 of file ConfigurationFolder.h.
References configurationFolder.
size_t ConfigurationFolder::numberOfChildren () [inline]
Return the number of children in this node.
Definition at line 45 of file ConfigurationFolder.h.
References m_childNodes.
Referenced by ConfigurationInstance::internalSearchNode(), and ConfigurationWriter::outputNode().
Member Data Documentation
std::vector<ConfigurationNode*> ConfigurationFolder::m_childNodes [private]
Definition at line 15 of file ConfigurationFolder.h.
Referenced by addChild(), freeChildren(), getChild(), and numberOfChildren().
The documentation for this class was generated from the following files:
Code/Configure/ConfigurationFolder.h
Code/Configure/ConfigurationFolder.cpp