Virtus: Filesystem Class Reference
Filesystem Class Reference
#include <Filesystem.h>
Static Public Member Functions
static FilesystemNode * evaluateChild (Folder *Target, const char *targetFile)
static FilesystemNode * search (const char *targetFile)
static DataInputStream * getFileInputStream (const char *targetFile)
static DataOutputStream * getFileOutputStream (const char *targetFile)
static Folder * getRoot ()
Detailed Description
Filesystem stores the root of the filesystem and the utility functions to access input and output streams
Definition at line 11 of file Filesystem.h.
Member Function Documentation
FilesystemNode * Filesystem::evaluateChild (Folder * Target, const char * targetFile) [static]
Search for the child node from the specified root
Parameters:
Folder* Parent the parent/root of the search (Usually Filesystem::getRoot())
const char* TargetFile the file
Returns:
FilesystemNode* The node found, or null if it's not found
Definition at line 6 of file Filesystem.cpp.
References folderId, FilesystemNode::getType(), and Folder::searchForChild().
Referenced by TextureMonitor::f_loadEntity(), LogWriter::getPathToLogFile(), GEngine::initialize(), InterfaceLayer::InterfaceLayer(), search(), TerrainNode::TerrainNode(), and TestNode::TestNode().
DataInputStream * Filesystem::getFileInputStream (const char * targetFile) [static]
Open a input stream to the specified file
Parameters:
Folder* searchRoot The root of the search
const char* TargetFile the file to open a input stream to
Returns:
DataInputStream* The input stream to the file - has not been opened
Definition at line 51 of file Filesystem.cpp.
References File::createInputStream(), fileId, FilesystemNode::getType(), and search().
DataOutputStream * Filesystem::getFileOutputStream (const char * targetFile) [static]
Open a output stream to the specified file
Parameters:
Folder* searchRoot The root of the search
const char* TargetFile the file to open a output stream to
Returns:
DataInputStream* The output stream to the file - has not been opened
Definition at line 73 of file Filesystem.cpp.
References File::createOutputStream(), fileId, FilesystemNode::getType(), and search().
Folder * Filesystem::getRoot () [static]
Get the root of the filesystem
Returns:
Folder* root of the FS
Definition at line 97 of file Filesystem.cpp.
References Folder::refresh().
Referenced by TextureMonitor::f_loadEntity(), LogWriter::getPathToLogFile(), GEngine::initialize(), InterfaceLayer::InterfaceLayer(), search(), TerrainNode::TerrainNode(), and TestNode::TestNode().
FilesystemNode * Filesystem::search (const char * targetFile) [static]
Search for a child node in the filesystem
Parameters:
TargetPath
Returns:
FilesystemNode* The node found, or null if it's not found
Definition at line 47 of file Filesystem.cpp.
References evaluateChild(), and getRoot().
Referenced by getFileInputStream(), and getFileOutputStream().
The documentation for this class was generated from the following files:
Code/Filesystem/Filesystem.h
Code/Filesystem/Filesystem.cpp