Virtus: RenderWindow Class Reference
RenderWindow Class Reference
#include <Window.h>
Public Member Functions
virtual ~RenderWindow ()
virtual int getWidth ()
virtual int getHeight ()
virtual bool create (const char *Title, int Width, int Height, GRenderer *)
virtual void setTitle (const char *newTitle)
virtual void setDimensions (unsigned int width, unsigned int height)
virtual void setFullscreen (bool value)
virtual void setInputPostbox (Postbox< Input_Event > *nPb)
virtual void update ()
virtual void finalFrame ()
Detailed Description
Definition at line 10 of file Window.h.
Constructor & Destructor Documentation
virtual RenderWindow::~RenderWindow () [inline, virtual]
Definition at line 13 of file Window.h.
Member Function Documentation
virtual bool RenderWindow::create (const char * Title, int Width, int Height, GRenderer *) [inline, virtual]
Reimplemented in GWindowGLX.
Definition at line 25 of file Window.h.
Referenced by GRenderer::initialize().
virtual void RenderWindow::finalFrame () [inline, virtual]
Reimplemented in GWindowGLX.
Definition at line 37 of file Window.h.
Referenced by GRenderer::end().
virtual int RenderWindow::getHeight () [inline, virtual]
Reimplemented in GWindowGLX.
Definition at line 20 of file Window.h.
Referenced by GRenderer::begin(), and GEngine::processEvent().
virtual int RenderWindow::getWidth () [inline, virtual]
Reimplemented in GWindowGLX.
Definition at line 15 of file Window.h.
Referenced by GRenderer::begin(), and GEngine::processEvent().
virtual void RenderWindow::setDimensions (unsigned int width, unsigned int height) [inline, virtual]
Reimplemented in GWindowGLX.
Definition at line 31 of file Window.h.
Referenced by GEngine::initialize().
virtual void RenderWindow::setFullscreen (bool value) [inline, virtual]
Reimplemented in GWindowGLX.
Definition at line 32 of file Window.h.
Referenced by GEngine::initialize().
virtual void RenderWindow::setInputPostbox (Postbox< Input_Event > * nPb) [inline, virtual]
Reimplemented in GWindowGLX.
Definition at line 34 of file Window.h.
Referenced by GEngine::initialize().
virtual void RenderWindow::setTitle (const char * newTitle) [inline, virtual]
Reimplemented in GWindowGLX.
Definition at line 30 of file Window.h.
Referenced by GEngine::initialize().
virtual void RenderWindow::update () [inline, virtual]
Reimplemented in GWindowGLX.
Definition at line 36 of file Window.h.
Referenced by GRenderer::begin().
The documentation for this class was generated from the following file:
Code/Render/GraphicsAPI/Window.h