Virtus: FilesystemNode Class Reference
FilesystemNode Class Reference
#include <Node.h>
Public Member Functions
virtual ~FilesystemNode ()
virtual int getType ()=0
virtual char * getName ()=0
Detailed Description
Definition at line 4 of file Node.h.
Constructor & Destructor Documentation
virtual FilesystemNode::~FilesystemNode () [inline, virtual]
Definition at line 8 of file Node.h.
Member Function Documentation
virtual char* FilesystemNode::getName () [pure virtual]
Implemented in LocalFile, and LocalFolder.
Referenced by FREngine::Load(), and LogWriter::LogWriter().
virtual int FilesystemNode::getType () [pure virtual]
Implemented in File, and Folder.
Referenced by Filesystem::evaluateChild(), TextureMonitor::f_loadEntity(), Filesystem::getFileInputStream(), and Filesystem::getFileOutputStream().
The documentation for this class was generated from the following file:
Code/Filesystem/Node.h