Virtus: Texture Class Reference
Texture Class Reference
#include <Texture.h>
Public Member Functions
Texture ()
virtual ~Texture ()
virtual void loadTextureData (InputDataFormat format, unsigned int width, unsigned int height, bool generateMipMaps, void *inputData)=0
virtual void makeActive ()=0
unsigned int getWidth ()
unsigned int getHeight ()
Protected Attributes
unsigned int m_textureWidth
unsigned int m_textureHeight
Detailed Description
Definition at line 17 of file Texture.h.
Constructor & Destructor Documentation
Texture::Texture () [inline]
Definition at line 25 of file Texture.h.
References m_textureHeight, and m_textureWidth.
virtual Texture::~Texture () [inline, virtual]
Definition at line 31 of file Texture.h.
Member Function Documentation
unsigned int Texture::getHeight () [inline]
Definition at line 44 of file Texture.h.
References m_textureHeight.
Referenced by InterfaceLayer::drawQuadWithUIElement().
unsigned int Texture::getWidth () [inline]
Definition at line 39 of file Texture.h.
References m_textureWidth.
Referenced by InterfaceLayer::drawQuadWithUIElement().
virtual void Texture::loadTextureData (InputDataFormat format, unsigned int width, unsigned int height, bool generateMipMaps, void * inputData) [pure virtual]
Implemented in GLTexture.
Referenced by TextureLoader::loadCompressedTGA(), FREngine::LoadFontmap(), TextureLoader::loadUncompressedTGA(), and TerrainNode::recalculateLightMaps().
virtual void Texture::makeActive () [pure virtual]
Implemented in GLTexture.
Referenced by WorldNode::draw(), InterfaceLayer::drawQuadWithUIElement(), and FontMap::Render().
Member Data Documentation
unsigned int Texture::m_textureHeight [protected]
Definition at line 21 of file Texture.h.
Referenced by getHeight(), GLTexture::loadTextureData(), and Texture().
unsigned int Texture::m_textureWidth [protected]
Definition at line 21 of file Texture.h.
Referenced by getWidth(), GLTexture::loadTextureData(), and Texture().
The documentation for this class was generated from the following file:
Code/Render/GraphicsAPI/Texture.h