Virtus: TextureLoader Class Reference
TextureLoader Class Reference
#include <TextureLoader.h>
Public Member Functions
bool load (Texture *Tex, DataInputStream *inStream)
Private Member Functions
bool loadCompressedTGA (Texture *Tex, DataInputStream *f, tga_header *head)
bool loadUncompressedTGA (Texture *Tex, DataInputStream *f, tga_header *head)
Detailed Description
Definition at line 33 of file TextureLoader.h.
Member Function Documentation
bool TextureLoader::load (Texture * Tex, DataInputStream * inStream)
Definition at line 4 of file TextureLoader.cpp.
References tga_header::height, tga_header::imageType, DataInputStream::isOpen(), loadCompressedTGA(), loadUncompressedTGA(), DataInputStream::read(), tga_header::width, tga_header::xStart, and tga_header::yStart.
Referenced by TextureMonitor::f_loadEntity().
bool TextureLoader::loadCompressedTGA (Texture * Tex, DataInputStream * f, tga_header * head) [private]
Definition at line 97 of file TextureLoader.cpp.
References tga_header::bits, tga_header::height, input_data_byte_rgb, input_data_byte_rgba, Texture::loadTextureData(), DataInputStream::read(), swapYRows(), tga_header::width, and tga_header::yStart.
Referenced by load().
bool TextureLoader::loadUncompressedTGA (Texture * Tex, DataInputStream * f, tga_header * head) [private]
Definition at line 305 of file TextureLoader.cpp.
References tga_header::bits, tga_header::height, input_data_byte_rgb, input_data_byte_rgba, Texture::loadTextureData(), DataInputStream::read(), swapYRows(), tga_header::width, and tga_header::yStart.
Referenced by load().
The documentation for this class was generated from the following files:
Code/Render/TextureMonitor/TextureLoader.h
Code/Render/TextureMonitor/TextureLoader.cpp