Virtus: ModelViewer Class Reference
ModelViewer Class Reference
#include <ViewerApplication.h>
Public Member Functions
bool onLoad (GEngine *Engine)
Called the first time the app is loaded, initialisation should be done here.
bool onUnload ()
Called when the app is unloaded, deinitilization should be done here.
void updateApplication (float seconds)
Called once per frame with the time that has elapsed since the last frame in seconds.
Private Attributes
bool m_Forward
bool m_Backward
bool m_Left
bool m_Right
bool m_Up
bool m_Down
SceneNode * m_worldNode
PressedEventHandler * ForwardHandle
ReleasedEventHandler * ForwardReleaseHandle
PressedEventHandler * LeftHandle
ReleasedEventHandler * LeftReleaseHandle
PressedEventHandler * RightHandle
ReleasedEventHandler * RightReleaseHandle
PressedEventHandler * BackwardHandle
ReleasedEventHandler * BackwardReleaseHandle
PressedEventHandler * UpHandle
ReleasedEventHandler * UpReleaseHandle
PressedEventHandler * DownHandle
ReleasedEventHandler * DownReleaseHandle
CloseHandler * windowCloseHandler
ToggleWireframeHandler * m_toggleWireframeHandler
IElement * m_viewerInterface
IElement * m_wireframeButton
GEngine * m_gameEngine
Detailed Description
Definition at line 11 of file ViewerApplication.h.
Member Function Documentation
bool ModelViewer::onLoad (GEngine * Engine) [virtual]
Called the first time the app is loaded, initialisation should be done here.
Implements GApplication.
Definition at line 23 of file ViewerApplication.cpp.
References SceneNode::addChildNode(), InterfaceLayer::AddElement(), BackwardHandle, BackwardReleaseHandle, GEngine::bindEvent(), DownHandle, DownReleaseHandle, EVENT_CLOSE, EVENT_MOVE_BACKWARD, EVENT_MOVE_BACKWARD_STOP, EVENT_MOVE_DOWN, EVENT_MOVE_DOWN_STOP, EVENT_MOVE_FORWARD, EVENT_MOVE_FORWARD_STOP, EVENT_MOVE_UP, EVENT_MOVE_UP_STOP, EVENT_ROTATE_LEFT, EVENT_ROTATE_LEFT_STOP, EVENT_ROTATE_RIGHT, EVENT_ROTATE_RIGHT_STOP, EVENT_WIREFRAME_TOGGLE, EVENTS_END, ForwardHandle, ForwardReleaseHandle, GRenderer::get3DLayer(), ThreeDRenderLayer::getActiveCamera(), GEngine::getEventManager(), GEngine::getInstance(), GRenderer::getInterfaceManager(), GRenderer::getLayer(), SceneNode::getPosition(), GRenderer::getRenderer(), input_event_keypressed, input_event_keyreleased, input_event_window, KEY_A, KEY_D, KEY_E, KEY_K, KEY_Q, KEY_S, KEY_W, Layer_3D, Layer_Interface, LeftHandle, LeftReleaseHandle, TestNode::load(), m_Backward, m_Down, m_Forward, m_gameEngine, m_Left, m_Right, m_toggleWireframeHandler, m_Up, m_viewerInterface, m_wireframeButton, m_worldNode, Camera::move(), EventManager::registerEventCallback(), RightHandle, RightReleaseHandle, EventManager::setNumberOfEvents(), Button::setOnMouseUp(), ThreeDRenderLayer::setWorldNode(), Vector3f::setX(), Vector3f::setY(), Vector3f::setZ(), toggleWireframeFn(), UpHandle, UpReleaseHandle, WINDOW_KILL_REQUEST, and windowCloseHandler.
bool ModelViewer::onUnload () [virtual]
Called when the app is unloaded, deinitilization should be done here.
Implements GApplication.
Definition at line 148 of file ViewerApplication.cpp.
References BackwardHandle, BackwardReleaseHandle, DownHandle, DownReleaseHandle, EVENT_MOVE_BACKWARD, EVENT_MOVE_BACKWARD_STOP, EVENT_MOVE_DOWN, EVENT_MOVE_DOWN_STOP, EVENT_MOVE_FORWARD, EVENT_MOVE_FORWARD_STOP, EVENT_MOVE_UP, EVENT_MOVE_UP_STOP, EVENT_ROTATE_LEFT, EVENT_ROTATE_LEFT_STOP, EVENT_ROTATE_RIGHT, EVENT_ROTATE_RIGHT_STOP, EVENT_WIREFRAME_TOGGLE, ForwardHandle, ForwardReleaseHandle, GEngine::getEventManager(), GRenderer::getInterfaceManager(), GRenderer::getLayer(), GRenderer::getRenderer(), Layer_3D, LeftHandle, LeftReleaseHandle, m_gameEngine, m_toggleWireframeHandler, m_viewerInterface, m_wireframeButton, m_worldNode, InterfaceLayer::RemoveElement(), RightHandle, RightReleaseHandle, ThreeDRenderLayer::setWorldNode(), EventManager::unregisterEventCallback(), UpHandle, and UpReleaseHandle.
void ModelViewer::updateApplication (float seconds) [virtual]
Called once per frame with the time that has elapsed since the last frame in seconds.
Implements GApplication.
Definition at line 232 of file ViewerApplication.cpp.
References ThreeDRenderLayer::getActiveCamera(), GRenderer::getLayer(), GRenderer::getRenderer(), Camera::getRotation(), Vector3f::getX(), Vector3f::getY(), Layer_3D, m_Backward, m_Down, m_Forward, m_Left, m_Right, m_Up, Camera::move(), Camera::rotate(), viewerMoveSpeed, and viewerRotateSpeed.
Member Data Documentation
PressedEventHandler* ModelViewer::BackwardHandle [private]
Definition at line 33 of file ViewerApplication.h.
Referenced by onLoad(), and onUnload().
ReleasedEventHandler* ModelViewer::BackwardReleaseHandle [private]
Definition at line 34 of file ViewerApplication.h.
Referenced by onLoad(), and onUnload().
PressedEventHandler* ModelViewer::DownHandle [private]
Definition at line 39 of file ViewerApplication.h.
Referenced by onLoad(), and onUnload().
ReleasedEventHandler* ModelViewer::DownReleaseHandle [private]
Definition at line 40 of file ViewerApplication.h.
Referenced by onLoad(), and onUnload().
PressedEventHandler* ModelViewer::ForwardHandle [private]
Definition at line 24 of file ViewerApplication.h.
Referenced by onLoad(), and onUnload().
ReleasedEventHandler* ModelViewer::ForwardReleaseHandle [private]
Definition at line 25 of file ViewerApplication.h.
Referenced by onLoad(), and onUnload().
PressedEventHandler* ModelViewer::LeftHandle [private]
Definition at line 27 of file ViewerApplication.h.
Referenced by onLoad(), and onUnload().
ReleasedEventHandler* ModelViewer::LeftReleaseHandle [private]
Definition at line 28 of file ViewerApplication.h.
Referenced by onLoad(), and onUnload().
bool ModelViewer::m_Backward [private]
Definition at line 16 of file ViewerApplication.h.
Referenced by onLoad(), and updateApplication().
bool ModelViewer::m_Down [private]
Definition at line 20 of file ViewerApplication.h.
Referenced by onLoad(), and updateApplication().
bool ModelViewer::m_Forward [private]
Definition at line 15 of file ViewerApplication.h.
Referenced by onLoad(), and updateApplication().
GEngine* ModelViewer::m_gameEngine [private]
Definition at line 49 of file ViewerApplication.h.
Referenced by onLoad(), and onUnload().
bool ModelViewer::m_Left [private]
Definition at line 17 of file ViewerApplication.h.
Referenced by onLoad(), and updateApplication().
bool ModelViewer::m_Right [private]
Definition at line 18 of file ViewerApplication.h.
Referenced by onLoad(), and updateApplication().
ToggleWireframeHandler* ModelViewer::m_toggleWireframeHandler [private]
Definition at line 44 of file ViewerApplication.h.
Referenced by onLoad(), and onUnload().
bool ModelViewer::m_Up [private]
Definition at line 19 of file ViewerApplication.h.
Referenced by onLoad(), and updateApplication().
IElement* ModelViewer::m_viewerInterface [private]
Definition at line 46 of file ViewerApplication.h.
Referenced by onLoad(), and onUnload().
IElement* ModelViewer::m_wireframeButton [private]
Definition at line 47 of file ViewerApplication.h.
Referenced by onLoad(), and onUnload().
SceneNode* ModelViewer::m_worldNode [private]
Definition at line 22 of file ViewerApplication.h.
Referenced by onLoad(), and onUnload().
PressedEventHandler* ModelViewer::RightHandle [private]
Definition at line 30 of file ViewerApplication.h.
Referenced by onLoad(), and onUnload().
ReleasedEventHandler* ModelViewer::RightReleaseHandle [private]
Definition at line 31 of file ViewerApplication.h.
Referenced by onLoad(), and onUnload().
PressedEventHandler* ModelViewer::UpHandle [private]
Definition at line 36 of file ViewerApplication.h.
Referenced by onLoad(), and onUnload().
ReleasedEventHandler* ModelViewer::UpReleaseHandle [private]
Definition at line 37 of file ViewerApplication.h.
Referenced by onLoad(), and onUnload().
CloseHandler* ModelViewer::windowCloseHandler [private]
Definition at line 42 of file ViewerApplication.h.
Referenced by onLoad().
The documentation for this class was generated from the following files:
Code/3DViewer/ViewerApplication.h
Code/3DViewer/ViewerApplication.cpp