Virtus: IElements::Button Class Reference
IElements::Button Class Reference
#include <Button.h>
Public Member Functions
Button (float x, float y, float w, float h, const char *BtnNormalText, const char *BtnOverText, const char *BtnDownText, Colour textClr, Colour bgNormal, Colour mouseOver, Colour mouseDown)
~Button ()
void draw (InterfaceLayer *IL)
bool handleInput (Input_Event e)
void setOnMouseUp (void(*onUpFn)(Button *Btn))
Protected Member Functions
virtual void onDown ()
void onUp ()
void handleButtonEvent (Input_Event e)
Protected Attributes
unsigned int m_textPointSize
Colour m_textColour
Colour m_normalBg
Colour m_btnDownBg
Colour m_mouseOverBg
bool m_mouseOverElement
bool m_mouseDownOverElement
void(* onUpFn)(Button *Btn)
char * m_buttonNormalText
char * m_mouseOverText
char * m_mouseDownText
Detailed Description
Definition at line 10 of file Button.h.
Constructor & Destructor Documentation
IElements::Button::Button (float x, float y, float w, float h, const char * BtnNormalText, const char * BtnOverText, const char * BtnDownText, Colour textClr, Colour bgNormal, Colour mouseOver, Colour mouseDown)
Definition at line 6 of file Button.cpp.
References m_btnDownBg, m_buttonNormalText, m_mouseDownOverElement, m_mouseDownText, m_mouseOverBg, m_mouseOverText, m_normalBg, m_textColour, and onUpFn.
IElements::Button::~Button ()
Definition at line 27 of file Button.cpp.
Member Function Documentation
void IElements::Button::draw (InterfaceLayer * IL) [virtual]
Reimplemented from IElement.
Definition at line 36 of file Button.cpp.
References GraphicsAPI::disableBlending(), InterfaceLayer::drawQuadWithUIElement(), GraphicsAPI::enableBlending(), InterfaceLayer::getDefaultTextRenderer(), GRenderer::getGraphicsAPI(), GRenderer::getRenderer(), height, FREngine::Render(), and width.
void IElements::Button::handleButtonEvent (Input_Event e) [protected]
Definition at line 101 of file Button.cpp.
References Input_Event::Event_Data, MOUSE_DOWN, MOUSE_MOTION, and MOUSE_UP.
bool IElements::Button::handleInput (Input_Event e) [virtual]
Reimplemented from IElement.
Definition at line 145 of file Button.cpp.
References Input_Event::Event_Data, Input_Event::Event_ID, height, input_event_button_one, and width.
virtual void IElements::Button::onDown () [inline, protected, virtual]
Definition at line 25 of file Button.h.
void IElements::Button::onUp () [protected]
Definition at line 137 of file Button.cpp.
void IElements::Button::setOnMouseUp (void(*)(Button *Btn) onUpFn)
Definition at line 132 of file Button.cpp.
Referenced by ModelViewer::onLoad().
Member Data Documentation
Colour IElements::Button::m_btnDownBg [protected]
Definition at line 17 of file Button.h.
Referenced by Button().
char* IElements::Button::m_buttonNormalText [protected]
Definition at line 30 of file Button.h.
Referenced by Button().
bool IElements::Button::m_mouseDownOverElement [protected]
Definition at line 21 of file Button.h.
Referenced by Button().
char* IElements::Button::m_mouseDownText [protected]
Definition at line 32 of file Button.h.
Referenced by Button().
Colour IElements::Button::m_mouseOverBg [protected]
Definition at line 18 of file Button.h.
Referenced by Button().
bool IElements::Button::m_mouseOverElement [protected]
Definition at line 20 of file Button.h.
char* IElements::Button::m_mouseOverText [protected]
Definition at line 31 of file Button.h.
Referenced by Button().
Colour IElements::Button::m_normalBg [protected]
Definition at line 16 of file Button.h.
Referenced by Button().
Colour IElements::Button::m_textColour [protected]
Definition at line 15 of file Button.h.
Referenced by Button().
unsigned int IElements::Button::m_textPointSize [protected]
Definition at line 14 of file Button.h.
void(* IElements::Button::onUpFn)(Button *Btn) [protected]
Definition at line 23 of file Button.h.
Referenced by Button().
The documentation for this class was generated from the following files:
Code/Render/Interface/Button.h
Code/Render/Interface/Button.cpp