Virtus: Mutex Class Reference
Mutex Class Reference
#include <Mutex.h>
Public Member Functions
Mutex ()
~Mutex ()
int Lock ()
int Unlock ()
int TryLock ()
Detailed Description
Definition at line 14 of file Mutex.h.
Constructor & Destructor Documentation
Mutex::Mutex ()
Mutex::~Mutex ()
Member Function Documentation
int Mutex::Lock ()
Referenced by BeeHive::allIdle(), BeeHive::beeRequestNextJob(), WorkerBee::getBeeStatus(), BeeHive::issueOrders(), Lock::Lock(), WorkerBee::Run(), and WorkerBee::WorkerBee().
int Mutex::TryLock ()
int Mutex::Unlock ()
Referenced by BeeHive::allIdle(), BeeHive::beeRequestNextJob(), WorkerBee::getBeeStatus(), BeeHive::issueOrders(), WorkerBee::Run(), WorkerBee::WorkerBee(), and Lock::~Lock().
The documentation for this class was generated from the following file:
Code/HIVE/Mutex.h