Virtus: ThreeDRenderLayer Class Reference
ThreeDRenderLayer Class Reference
#include <3DRenderLayer.h>
Public Member Functions
ThreeDRenderLayer ()
~ThreeDRenderLayer ()
void draw (GRenderer *renderer, int width, int height)
void update (float seconds)
void setWorldNode (SceneNode *worldNode)
Set the active world node, pass NULL if you don't want a world to be rendered.
Camera * getActiveCamera ()
Private Attributes
Camera m_worldCamera
SceneNode * m_worldNode
Detailed Description
Definition at line 9 of file 3DRenderLayer.h.
Constructor & Destructor Documentation
ThreeDRenderLayer::ThreeDRenderLayer ()
Definition at line 4 of file 3DRenderLayer.cpp.
References m_worldNode.
ThreeDRenderLayer::~ThreeDRenderLayer ()
Definition at line 9 of file 3DRenderLayer.cpp.
Member Function Documentation
void ThreeDRenderLayer::draw (GRenderer * renderer, int width, int height) [virtual]
Reimplemented from GRenderLayer.
Definition at line 13 of file 3DRenderLayer.cpp.
References SceneNode::draw(), GRenderer::getGraphicsAPI(), GRenderer::getRenderer(), GRenderer::getRenderWireframeValue(), m_worldCamera, m_worldNode, GraphicsAPI::resetMatrix(), GraphicsAPI::setupFor3D(), and GraphicsAPI::setWireframeRender().
Camera* ThreeDRenderLayer::getActiveCamera () [inline]
Definition at line 28 of file 3DRenderLayer.h.
References m_worldCamera.
Referenced by TerrainNode::draw(), ModelViewer::onLoad(), and ModelViewer::updateApplication().
void ThreeDRenderLayer::setWorldNode (SceneNode * worldNode)
Set the active world node, pass NULL if you don't want a world to be rendered.
Definition at line 46 of file 3DRenderLayer.cpp.
References m_worldNode.
Referenced by ModelViewer::onLoad(), and ModelViewer::onUnload().
void ThreeDRenderLayer::update (float seconds) [virtual]
Reimplemented from GRenderLayer.
Definition at line 38 of file 3DRenderLayer.cpp.
References m_worldNode, and SceneNode::update().
Member Data Documentation
Camera ThreeDRenderLayer::m_worldCamera [private]
Definition at line 14 of file 3DRenderLayer.h.
Referenced by draw(), and getActiveCamera().
SceneNode* ThreeDRenderLayer::m_worldNode [private]
Definition at line 15 of file 3DRenderLayer.h.
Referenced by draw(), setWorldNode(), ThreeDRenderLayer(), and update().
The documentation for this class was generated from the following files:
Code/Render/3D/3DRenderLayer.h
Code/Render/3D/3DRenderLayer.cpp