Virtus: ViewerUserInterface Class Reference
ViewerUserInterface Class Reference
#include <UserInterface.h>
Public Member Functions
ViewerUserInterface ()
void draw (InterfaceLayer *IL)
bool handleInput (Input_Event e)
Detailed Description
Definition at line 9 of file UserInterface.h.
Constructor & Destructor Documentation
ViewerUserInterface::ViewerUserInterface ()
Definition at line 6 of file UserInterface.cpp.
Member Function Documentation
void ViewerUserInterface::draw (InterfaceLayer * IL) [virtual]
Implements IElement.
Definition at line 10 of file UserInterface.cpp.
References GraphicsAPI::disableBlending(), GraphicsAPI::enableBlending(), InterfaceLayer::getDefaultTextRenderer(), FPSCalculator::getFPS(), GEngine::getFpsCalculator(), GRenderer::getGraphicsAPI(), GEngine::getInstance(), GRenderer::getRenderer(), IElement::height, FREngine::Render(), IElement::width, IElement::x, and IElement::y.
bool ViewerUserInterface::handleInput (Input_Event e) [inline, virtual]
Implements IElement.
Definition at line 16 of file UserInterface.h.
The documentation for this class was generated from the following files:
Code/3DViewer/UserInterface.h
Code/3DViewer/UserInterface.cpp