Virtus: ConfigurationNode Class Reference
ConfigurationNode Class Reference
#include <ConfigurationNode.h>
Public Member Functions
ConfigurationNode (const char *Name)
virtual ~ConfigurationNode ()
virtual int getType ()
const char * getName ()
Private Attributes
char * m_nodeName
Detailed Description
Definition at line 19 of file ConfigurationNode.h.
Constructor & Destructor Documentation
ConfigurationNode::ConfigurationNode (const char * Name)
Definition at line 3 of file ConfigurationNode.cpp.
References m_nodeName.
ConfigurationNode::~ConfigurationNode () [virtual]
Definition at line 10 of file ConfigurationNode.cpp.
References m_nodeName.
Member Function Documentation
const char* ConfigurationNode::getName () [inline]
Definition at line 31 of file ConfigurationNode.h.
References m_nodeName.
Referenced by ConfigurationInstance::internalSearchNode(), and ConfigurationWriter::outputNode().
virtual int ConfigurationNode::getType () [inline, virtual]
Reimplemented in ConfigurationFolder, ConfigurationNumber, and ConfigurationString.
Definition at line 30 of file ConfigurationNode.h.
References configurationError.
Referenced by GEngine::initialize(), ConfigurationInstance::internalSearchNode(), and ConfigurationWriter::outputNode().
Member Data Documentation
char* ConfigurationNode::m_nodeName [private]
Definition at line 23 of file ConfigurationNode.h.
Referenced by ConfigurationNode(), getName(), and ~ConfigurationNode().
The documentation for this class was generated from the following files:
Code/Configure/ConfigurationNode.h
Code/Configure/ConfigurationNode.cpp