Virtus: DataInputStream Class Reference
DataInputStream Class Reference
#include <Stream.h>
Public Member Functions
virtual ~DataInputStream ()
virtual bool isOpen ()=0
virtual bool open (bool textMode)=0
virtual void close ()=0
virtual bool read (void *targetLocation, unsigned long len)=0
virtual bool skip (unsigned long bytes)=0
virtual bool rewind (unsigned long bytes)=0
Detailed Description
Definition at line 4 of file Stream.h.
Constructor & Destructor Documentation
virtual DataInputStream::~DataInputStream () [inline, virtual]
Definition at line 11 of file Stream.h.
Member Function Documentation
virtual void DataInputStream::close () [pure virtual]
Implemented in LocalDataInputStream.
virtual bool DataInputStream::isOpen () [pure virtual]
Implemented in LocalDataInputStream.
Referenced by TextureLoader::load().
virtual bool DataInputStream::open (bool textMode) [pure virtual]
Implemented in LocalDataInputStream.
Referenced by TextureMonitor::f_loadEntity(), FREngine::Load(), ConfigurationInstance::loadFromPath(), and GLShaderFactory::loadShader().
virtual bool DataInputStream::read (void * targetLocation, unsigned long len) [pure virtual]
Implemented in LocalDataInputStream.
Referenced by ConfigurationReader::getNextWord(), ConfigurationReader::getString(), TextureLoader::load(), FREngine::Load(), TextureLoader::loadCompressedTGA(), GLShaderFactory::loadShader(), TextureLoader::loadUncompressedTGA(), and ConfigurationReader::skipWhitespace().
virtual bool DataInputStream::rewind (unsigned long bytes) [pure virtual]
Implemented in LocalDataInputStream.
Referenced by ConfigurationReader::getNextWord(), and ConfigurationReader::skipWhitespace().
virtual bool DataInputStream::skip (unsigned long bytes) [pure virtual]
Implemented in LocalDataInputStream.
The documentation for this class was generated from the following file:
Code/Filesystem/Stream.h