Virtus: IElements::Checkbox Class Reference
IElements::Checkbox Class Reference
#include <Checkbox.h>
Public Member Functions
Checkbox (float x, float y, float w, float h, Colour m_downClr, Colour m_upClr)
~Checkbox ()
void draw (InterfaceLayer *IL)
bool handleInput (Input_Event e)
Protected Attributes
bool m_mouseOver
bool m_mouseDown
bool m_isChecked
Detailed Description
Definition at line 11 of file Checkbox.h.
Constructor & Destructor Documentation
IElements::Checkbox::Checkbox (float x, float y, float w, float h, Colour m_downClr, Colour m_upClr)
Definition at line 6 of file Checkbox.cpp.
References m_isChecked, m_mouseDown, and m_mouseOver.
IElements::Checkbox::~Checkbox ()
Definition at line 13 of file Checkbox.cpp.
Member Function Documentation
void IElements::Checkbox::draw (InterfaceLayer * IL) [virtual]
Reimplemented from IElement.
Definition at line 19 of file Checkbox.cpp.
References GraphicsAPI::disableBlending(), InterfaceLayer::drawQuadWithUIElement(), GraphicsAPI::enableBlending(), GRenderer::getGraphicsAPI(), GRenderer::getRenderer(), height, and width.
bool IElements::Checkbox::handleInput (Input_Event e) [virtual]
Reimplemented from IElement.
Definition at line 48 of file Checkbox.cpp.
References Input_Event::Event_Data, Input_Event::Event_ID, height, input_event_button_one, MOUSE_DOWN, MOUSE_UP, and width.
Member Data Documentation
bool IElements::Checkbox::m_isChecked [protected]
Definition at line 17 of file Checkbox.h.
Referenced by Checkbox().
bool IElements::Checkbox::m_mouseDown [protected]
Definition at line 16 of file Checkbox.h.
Referenced by Checkbox().
bool IElements::Checkbox::m_mouseOver [protected]
Definition at line 15 of file Checkbox.h.
Referenced by Checkbox().
The documentation for this class was generated from the following files:
Code/Render/Interface/Checkbox.h
Code/Render/Interface/Checkbox.cpp