Virtus: GEngine Class Reference
GEngine Class Reference
#include <GEngine.h>
Public Member Functions
~GEngine ()
void bindEvent (unsigned int Eve, input_event_ids, key_ids)
void sendEventManagerMessage (Input_Event iEvent)
void processEvent (Input_Event event)
bool isInErrorState ()
const char * errorDetails ()
int gameLoop ()
void killEngine ()
EventManager * getEventManager ()
FPSCalculator * getFpsCalculator ()
LogWriter * getLog ()
void pauseEngine ()
void unpauseEngine ()
void togglePaused ()
void pausePhysics ()
void unpausePhysics ()
void togglePhysics ()
bool loadApplication (GApplication *App)
bool unloadApplication ()
bool applicationLoaded ()
unsigned int getCanvasWidth ()
unsigned int getCanvasHeight ()
void doFrameUpdate (float seconds)
Static Public Member Functions
static GEngine * getInstance ()
Private Member Functions
bool initialize ()
void uninitialize ()
void initializeInputBindings ()
void freeInputBindings ()
void f_sleep ()
void setErrorDetails (const char *str)
GEngine ()
Private Attributes
FPSCalculator m_fpsCalculator
Clock m_clock
EventManager * m_eventManager
Postbox< Input_Event > m_inputPostbox
InputBinding * m_inputBindings
GApplication * m_currentApplication
ConfigurationInstance * m_engineCfg
BeeHive * m_threadHive
LogWriter * m_engineLog
bool m_GameActive
bool m_physicsActive
bool m_GamePaused
bool m_errorState
const char * m_errorDetails
unsigned int m_canvasWidth
unsigned int m_canvasHeight
Static Private Attributes
static const char * TAG = "Engine Core"
Detailed Description
Definition at line 31 of file GEngine.h.
Constructor & Destructor Documentation
GEngine::GEngine () [private]
Definition at line 21 of file GEngine.cpp.
References m_canvasHeight, m_canvasWidth, m_engineCfg, m_engineLog, m_errorDetails, m_errorState, m_eventManager, m_inputBindings, and m_threadHive.
Referenced by getInstance().
GEngine::~GEngine ()
Definition at line 38 of file GEngine.cpp.
References uninitialize().
Member Function Documentation
bool GEngine::applicationLoaded () [inline]
Definition at line 159 of file GEngine.h.
References m_currentApplication.
void GEngine::bindEvent (unsigned int Eve, input_event_ids id, key_ids key)
Definition at line 305 of file GEngine.cpp.
References EventBinding::Events, input_event_end, InputBinding::Keys, KEYS_END, and m_inputBindings.
Referenced by ModelViewer::onLoad().
void GEngine::doFrameUpdate (float seconds)
Definition at line 391 of file GEngine.cpp.
References GRenderer::getRenderer(), m_currentApplication, m_GamePaused, m_physicsActive, GRenderer::update(), and GApplication::updateApplication().
Referenced by gameLoop().
const char* GEngine::errorDetails () [inline]
Definition at line 84 of file GEngine.h.
References m_errorDetails.
Referenced by main().
void GEngine::f_sleep () [private]
Definition at line 314 of file GEngine.cpp.
References FPSCalculator::getFPS(), and m_fpsCalculator.
Referenced by gameLoop().
void GEngine::freeInputBindings () [private]
Definition at line 57 of file GEngine.cpp.
References input_event_end, InputBinding::Keys, and m_inputBindings.
Referenced by uninitialize().
int GEngine::gameLoop ()
Definition at line 416 of file GEngine.cpp.
References Clock::calculateElapsedTime(), doFrameUpdate(), f_sleep(), FPSCalculator::frame(), GRenderer::getRenderer(), Postbox< T >::HasNext(), Clock::initialize(), m_canvasHeight, m_canvasWidth, m_clock, m_errorState, m_fpsCalculator, m_GameActive, m_inputPostbox, m_physicsActive, processEvent(), Postbox< T >::ReadNext(), GRenderer::renderScene(), and setErrorDetails().
Referenced by main().
unsigned int GEngine::getCanvasHeight () [inline]
Definition at line 176 of file GEngine.h.
References m_canvasHeight.
unsigned int GEngine::getCanvasWidth () [inline]
Definition at line 172 of file GEngine.h.
References m_canvasWidth.
EventManager* GEngine::getEventManager () [inline]
Definition at line 95 of file GEngine.h.
References m_eventManager.
Referenced by ModelViewer::onLoad(), and ModelViewer::onUnload().
FPSCalculator* GEngine::getFpsCalculator () [inline]
Definition at line 102 of file GEngine.h.
References m_fpsCalculator.
Referenced by ViewerUserInterface::draw().
GEngine * GEngine::getInstance () [static]
Definition at line 511 of file GEngine.cpp.
References GEngine(), and initialize().
Referenced by BeeHive::BeeHive(), ViewerUserInterface::draw(), main(), ModelViewer::onLoad(), LocalFolder::searchForChild(), CloseHandler::triggerCallback(), and BeeHive::~BeeHive().
LogWriter* GEngine::getLog () [inline]
Definition at line 109 of file GEngine.h.
References m_engineLog.
Referenced by BeeHive::BeeHive(), LocalFolder::searchForChild(), and BeeHive::~BeeHive().
bool GEngine::initialize (void) [private]
Definition at line 73 of file GEngine.cpp.
References configurationNumber, configurationString, defaultWindowHeight, defaultWindowTitle, defaultWindowWidth, Filesystem::evaluateChild(), InterfaceLayer::getDefaultTextRenderer(), GRenderer::getInterfaceManager(), ConfigurationInstance::getNode(), LogWriter::getPathToLogFile(), GRenderer::getRenderer(), Filesystem::getRoot(), ConfigurationString::getStringData(), ConfigurationNode::getType(), ConfigurationNumber::getValue(), GRenderer::getWindow(), initializeInputBindings(), FREngine::Load(), m_canvasHeight, m_canvasWidth, m_currentApplication, m_engineCfg, m_engineLog, m_eventManager, m_GameActive, m_GamePaused, m_inputBindings, m_inputPostbox, m_threadHive, RenderWindow::setDimensions(), setErrorDetails(), RenderWindow::setFullscreen(), RenderWindow::setInputPostbox(), RenderWindow::setTitle(), TAG, and LogWriter::writeLine().
Referenced by getInstance().
void GEngine::initializeInputBindings () [private]
Definition at line 44 of file GEngine.cpp.
References input_event_end, InputBinding::Keys, KEYS_END, and m_inputBindings.
Referenced by initialize().
bool GEngine::isInErrorState () [inline]
Definition at line 83 of file GEngine.h.
References m_errorState.
Referenced by main().
void GEngine::killEngine () [inline]
Definition at line 88 of file GEngine.h.
References m_GameActive.
Referenced by CloseHandler::triggerCallback().
bool GEngine::loadApplication (GApplication * App)
Definition at line 459 of file GEngine.cpp.
References m_currentApplication, m_errorState, GApplication::onLoad(), and setErrorDetails().
Referenced by main().
void GEngine::pauseEngine () [inline]
Definition at line 114 of file GEngine.h.
References m_GamePaused.
void GEngine::pausePhysics () [inline]
Definition at line 135 of file GEngine.h.
References m_physicsActive.
void GEngine::processEvent (Input_Event event)
Definition at line 350 of file GEngine.cpp.
References Input_Event::Event_ID, RenderWindow::getHeight(), GRenderer::getRenderer(), RenderWindow::getWidth(), GRenderer::getWindow(), input_event_button_one, input_event_button_two, m_canvasHeight, m_canvasWidth, and sendEventManagerMessage().
Referenced by gameLoop().
void GEngine::sendEventManagerMessage (Input_Event iEvent)
Definition at line 324 of file GEngine.cpp.
References Input_Event::Event_Data, Input_Event::Event_Flags, Input_Event::Event_ID, EventBinding::Events, InputBinding::Keys, m_eventManager, m_inputBindings, and EventManager::triggerEvent().
Referenced by processEvent().
void GEngine::setErrorDetails (const char * str) [private]
Definition at line 495 of file GEngine.cpp.
References m_engineLog, m_errorDetails, m_errorState, TAG, and LogWriter::writeLine().
Referenced by gameLoop(), initialize(), and loadApplication().
void GEngine::togglePaused () [inline]
Definition at line 128 of file GEngine.h.
References m_GamePaused.
void GEngine::togglePhysics () [inline]
Definition at line 149 of file GEngine.h.
References m_physicsActive.
void GEngine::uninitialize () [private]
Definition at line 268 of file GEngine.cpp.
References freeInputBindings(), m_engineCfg, m_engineLog, m_eventManager, m_threadHive, TAG, and LogWriter::writeLine().
Referenced by ~GEngine().
bool GEngine::unloadApplication ()
Definition at line 482 of file GEngine.cpp.
References m_currentApplication, and GApplication::onUnload().
Referenced by main().
void GEngine::unpauseEngine () [inline]
Definition at line 121 of file GEngine.h.
References m_GamePaused.
void GEngine::unpausePhysics () [inline]
Definition at line 142 of file GEngine.h.
References m_physicsActive.
Member Data Documentation
unsigned int GEngine::m_canvasHeight [private]
Definition at line 68 of file GEngine.h.
Referenced by gameLoop(), GEngine(), getCanvasHeight(), initialize(), and processEvent().
unsigned int GEngine::m_canvasWidth [private]
Definition at line 67 of file GEngine.h.
Referenced by gameLoop(), GEngine(), getCanvasWidth(), initialize(), and processEvent().
Clock GEngine::m_clock [private]
Definition at line 43 of file GEngine.h.
Referenced by gameLoop().
GApplication* GEngine::m_currentApplication [private]
Definition at line 50 of file GEngine.h.
Referenced by applicationLoaded(), doFrameUpdate(), initialize(), loadApplication(), and unloadApplication().
ConfigurationInstance* GEngine::m_engineCfg [private]
Definition at line 52 of file GEngine.h.
Referenced by GEngine(), initialize(), and uninitialize().
LogWriter* GEngine::m_engineLog [private]
Definition at line 56 of file GEngine.h.
Referenced by GEngine(), getLog(), initialize(), setErrorDetails(), and uninitialize().
const char* GEngine::m_errorDetails [private]
Definition at line 65 of file GEngine.h.
Referenced by errorDetails(), GEngine(), and setErrorDetails().
bool GEngine::m_errorState [private]
Definition at line 64 of file GEngine.h.
Referenced by gameLoop(), GEngine(), isInErrorState(), loadApplication(), and setErrorDetails().
EventManager* GEngine::m_eventManager [private]
Definition at line 45 of file GEngine.h.
Referenced by GEngine(), getEventManager(), initialize(), sendEventManagerMessage(), and uninitialize().
FPSCalculator GEngine::m_fpsCalculator [private]
Definition at line 41 of file GEngine.h.
Referenced by f_sleep(), gameLoop(), and getFpsCalculator().
bool GEngine::m_GameActive [private]
Definition at line 60 of file GEngine.h.
Referenced by gameLoop(), initialize(), and killEngine().
bool GEngine::m_GamePaused [private]
Definition at line 62 of file GEngine.h.
Referenced by doFrameUpdate(), initialize(), pauseEngine(), togglePaused(), and unpauseEngine().
InputBinding* GEngine::m_inputBindings [private]
Definition at line 48 of file GEngine.h.
Referenced by bindEvent(), freeInputBindings(), GEngine(), initialize(), initializeInputBindings(), and sendEventManagerMessage().
Postbox<Input_Event> GEngine::m_inputPostbox [private]
Definition at line 47 of file GEngine.h.
Referenced by gameLoop(), and initialize().
bool GEngine::m_physicsActive [private]
Definition at line 61 of file GEngine.h.
Referenced by doFrameUpdate(), gameLoop(), pausePhysics(), togglePhysics(), and unpausePhysics().
BeeHive* GEngine::m_threadHive [private]
Definition at line 54 of file GEngine.h.
Referenced by GEngine(), initialize(), and uninitialize().
const char * GEngine::TAG = "Engine Core" [static, private]
Definition at line 34 of file GEngine.h.
Referenced by initialize(), setErrorDetails(), and uninitialize().
The documentation for this class was generated from the following files:
Code/Core/GEngine.h
Code/Core/GEngine.cpp