Virtus: TerrainPatch Class Reference
TerrainPatch Class Reference
#include <TerrainPatch.h>
Public Member Functions
TerrainPatch (float *Heights, float *UV, unsigned int patchSize)
~TerrainPatch ()
void draw (unsigned int lod)
Private Member Functions
VertexSet * generateDrawLOD (float *heights, float *UV, unsigned int patchSize, unsigned int stride, unsigned int *lodPatchSize)
Private Attributes
VertexSet ** m_patchVSetLods
unsigned int * m_lodNumVs
unsigned int m_numLods
float m_patchSize
Detailed Description
Definition at line 5 of file TerrainPatch.h.
Constructor & Destructor Documentation
TerrainPatch::TerrainPatch (float * Heights, float * UV, unsigned int patchSize)
Definition at line 73 of file TerrainPatch.cpp.
References generateDrawLOD(), m_lodNumVs, m_numLods, and m_patchVSetLods.
TerrainPatch::~TerrainPatch ()
Definition at line 111 of file TerrainPatch.cpp.
References m_lodNumVs, m_numLods, and m_patchVSetLods.
Member Function Documentation
void TerrainPatch::draw (unsigned int lod)
Definition at line 123 of file TerrainPatch.cpp.
References VertexSet::Draw(), m_lodNumVs, m_numLods, m_patchVSetLods, and TRIANGLE_STRIP.
VertexSet * TerrainPatch::generateDrawLOD (float * heights, float * UV, unsigned int patchSize, unsigned int stride, unsigned int * lodPatchSize) [private]
Definition at line 4 of file TerrainPatch.cpp.
References GRenderer::getGraphicsAPI(), GRenderer::getRenderer(), GraphicsAPI::newVertexSet(), VertexSet::setTextureCoordinates(), and VertexSet::setVertices().
Referenced by TerrainPatch().
Member Data Documentation
unsigned int* TerrainPatch::m_lodNumVs [private]
Definition at line 11 of file TerrainPatch.h.
Referenced by draw(), TerrainPatch(), and ~TerrainPatch().
unsigned int TerrainPatch::m_numLods [private]
Definition at line 12 of file TerrainPatch.h.
Referenced by draw(), TerrainPatch(), and ~TerrainPatch().
float TerrainPatch::m_patchSize [private]
Definition at line 14 of file TerrainPatch.h.
VertexSet** TerrainPatch::m_patchVSetLods [private]
Definition at line 10 of file TerrainPatch.h.
Referenced by draw(), TerrainPatch(), and ~TerrainPatch().
The documentation for this class was generated from the following files:
Code/Render/3D/Terrain/TerrainPatch.h
Code/Render/3D/Terrain/TerrainPatch.cpp