Virtus: GLShader Class Reference
GLShader Class Reference
#include <GLShader.h>
Public Member Functions
GLShader ()
~GLShader ()
bool loadShader (const char *vert, const char *frag)
void activateShader ()
void deactivateShader ()
void setNumberOfTextures (unsigned int number)
void setTextureName (unsigned int i, const char *Name)
void setTexture (unsigned int i, Texture *tex)
Private Member Functions
void deleteShader ()
Private Attributes
unsigned int m_debugID
GLuint m_vertexShaderID
GLuint m_fragmentShaderID
GLuint m_shaderProgramID
GLuint * m_textureLocations
unsigned int m_numTextures
Detailed Description
Definition at line 7 of file GLShader.h.
Constructor & Destructor Documentation
GLShader::GLShader ()
Definition at line 9 of file GLShader.cpp.
References GRenderer::getRenderer(), GRenderer::getRenderLog(), m_debugID, m_fragmentShaderID, m_numTextures, m_shaderProgramID, m_textureLocations, m_vertexShaderID, and RenderLog::writeToLogFile().
GLShader::~GLShader ()
Definition at line 28 of file GLShader.cpp.
References GRenderer::getRenderer(), GRenderer::getRenderLog(), m_debugID, m_fragmentShaderID, m_numTextures, m_shaderProgramID, m_textureLocations, m_vertexShaderID, and RenderLog::writeToLogFile().
Member Function Documentation
void GLShader::activateShader () [virtual]
Implements Shader.
Definition at line 245 of file GLShader.cpp.
References m_shaderProgramID.
Referenced by setTexture(), and setTextureName().
void GLShader::deactivateShader () [virtual]
Implements Shader.
Definition at line 250 of file GLShader.cpp.
void GLShader::deleteShader () [private]
bool GLShader::loadShader (const char * vert, const char * frag)
Definition at line 56 of file GLShader.cpp.
References GRenderer::getRenderer(), GRenderer::getRenderLog(), m_fragmentShaderID, m_shaderProgramID, m_vertexShaderID, and RenderLog::writeToLogFile().
Referenced by GLShaderFactory::loadShader().
void GLShader::setNumberOfTextures (unsigned int number) [virtual]
Implements Shader.
Definition at line 176 of file GLShader.cpp.
References m_numTextures, and m_textureLocations.
void GLShader::setTexture (unsigned int i, Texture * tex) [virtual]
Implements Shader.
Definition at line 225 of file GLShader.cpp.
References activateShader(), m_numTextures, and m_shaderProgramID.
void GLShader::setTextureName (unsigned int i, const char * Name) [virtual]
Implements Shader.
Definition at line 210 of file GLShader.cpp.
References activateShader(), m_numTextures, m_shaderProgramID, and m_textureLocations.
Member Data Documentation
unsigned int GLShader::m_debugID [private]
Definition at line 11 of file GLShader.h.
Referenced by GLShader(), and ~GLShader().
GLuint GLShader::m_fragmentShaderID [private]
Definition at line 14 of file GLShader.h.
Referenced by GLShader(), loadShader(), and ~GLShader().
unsigned int GLShader::m_numTextures [private]
Definition at line 18 of file GLShader.h.
Referenced by GLShader(), setNumberOfTextures(), setTexture(), setTextureName(), and ~GLShader().
GLuint GLShader::m_shaderProgramID [private]
Definition at line 15 of file GLShader.h.
Referenced by activateShader(), GLShader(), loadShader(), setTexture(), setTextureName(), and ~GLShader().
GLuint* GLShader::m_textureLocations [private]
Definition at line 17 of file GLShader.h.
Referenced by GLShader(), setNumberOfTextures(), setTextureName(), and ~GLShader().
GLuint GLShader::m_vertexShaderID [private]
Definition at line 13 of file GLShader.h.
Referenced by GLShader(), loadShader(), and ~GLShader().
The documentation for this class was generated from the following files:
Code/Render/GraphicsAPI/GL2/GLShader.h
Code/Render/GraphicsAPI/GL2/GLShader.cpp