Virtus: GApplication Class Reference
GApplication Class Reference
Abstraction of a application that runs on the engine.
#include <Application.h>
Public Member Functions
virtual ~GApplication ()
virtual bool onLoad (GEngine *Engine)=0
Called the first time the app is loaded, initialisation should be done here.
virtual bool onUnload ()=0
Called when the app is unloaded, deinitilization should be done here.
virtual void updateApplication (float seconds)=0
Called once per frame with the time that has elapsed since the last frame in seconds.
Detailed Description
Abstraction of a application that runs on the engine.
Definition at line 10 of file Application.h.
Constructor & Destructor Documentation
virtual GApplication::~GApplication () [inline, virtual]
Definition at line 16 of file Application.h.
Member Function Documentation
virtual bool GApplication::onLoad (GEngine * Engine) [pure virtual]
Called the first time the app is loaded, initialisation should be done here.
Implemented in ModelViewer.
Referenced by GEngine::loadApplication().
virtual bool GApplication::onUnload () [pure virtual]
Called when the app is unloaded, deinitilization should be done here.
Implemented in ModelViewer.
Referenced by GEngine::unloadApplication().
virtual void GApplication::updateApplication (float seconds) [pure virtual]
Called once per frame with the time that has elapsed since the last frame in seconds.
Implemented in ModelViewer.
Referenced by GEngine::doFrameUpdate().
The documentation for this class was generated from the following file:
Code/API/Application.h