Virtus: DataOutputStream Class Reference
DataOutputStream Class Reference
#include <Stream.h>
Public Member Functions
virtual ~DataOutputStream ()
virtual bool isOpen ()=0
virtual bool open (bool textMode)=0
virtual void close ()=0
virtual bool write (const void *Data, unsigned long len)=0
virtual void flush ()=0
Detailed Description
Definition at line 22 of file Stream.h.
Constructor & Destructor Documentation
virtual DataOutputStream::~DataOutputStream () [inline, virtual]
Definition at line 27 of file Stream.h.
Member Function Documentation
virtual void DataOutputStream::close () [pure virtual]
Implemented in LocalDataOutputStream.
virtual void DataOutputStream::flush () [pure virtual]
Implemented in LocalDataOutputStream.
Referenced by LogWriter::writeLine().
virtual bool DataOutputStream::isOpen () [pure virtual]
Implemented in LocalDataOutputStream.
Referenced by LogWriter::writeLine().
virtual bool DataOutputStream::open (bool textMode) [pure virtual]
Implemented in LocalDataOutputStream.
Referenced by LogWriter::LogWriter(), and ConfigurationInstance::writeToPath().
virtual bool DataOutputStream::write (const void * Data, unsigned long len) [pure virtual]
Implemented in LocalDataOutputStream.
Referenced by LogWriter::writeLine(), and FsUtils::writeLineToStream().
The documentation for this class was generated from the following file:
Code/Filesystem/Stream.h