Virtus: Folder Class Reference
Folder Class Reference
#include <Folder.h>
Public Member Functions
virtual unsigned int numChildren ()=0
virtual FilesystemNode * getChild (unsigned int number)=0
virtual void refresh ()=0
virtual File * newChild (const char *Name)=0
virtual Folder * newChildFolder (const char *Name)=0
virtual FilesystemNode * searchForChild (const char *Name, unsigned int nameLength=0)=0
int getType ()
virtual ~Folder ()
Detailed Description
Definition at line 8 of file Folder.h.
Constructor & Destructor Documentation
virtual Folder::~Folder () [inline, virtual]
Definition at line 25 of file Folder.h.
Member Function Documentation
virtual FilesystemNode* Folder::getChild (unsigned int number) [pure virtual]
Implemented in LocalFolder.
int Folder::getType () [inline, virtual]
Implements FilesystemNode.
Definition at line 20 of file Folder.h.
References folderId.
Referenced by LogWriter::getPathToLogFile().
virtual File* Folder::newChild (const char * Name) [pure virtual]
Implemented in LocalFolder.
Referenced by LogWriter::getPathToLogFile().
virtual Folder* Folder::newChildFolder (const char * Name) [pure virtual]
Implemented in LocalFolder.
virtual unsigned int Folder::numChildren () [pure virtual]
Implemented in LocalFolder.
virtual void Folder::refresh () [pure virtual]
Implemented in LocalFolder.
Referenced by Filesystem::getRoot(), LocalFolder::newChildFolder(), and LocalFolder::refresh().
virtual FilesystemNode* Folder::searchForChild (const char * Name, unsigned int nameLength = 0) [pure virtual]
Implemented in LocalFolder.
Referenced by Filesystem::evaluateChild(), and LogWriter::getPathToLogFile().
The documentation for this class was generated from the following file:
Code/Filesystem/Folder.h