Virtus: ConfigurationWriter Class Reference
ConfigurationWriter Class Reference
#include <ConfigurationWriter.h>
Static Public Member Functions
static void outputNode (ConfigurationNode *Node, unsigned int depth, DataOutputStream *outs)
Static Private Member Functions
static void startNewLine (unsigned int depth, DataOutputStream *outs)
Detailed Description
Definition at line 6 of file ConfigurationWriter.h.
Member Function Documentation
void ConfigurationWriter::outputNode (ConfigurationNode * Node, unsigned int depth, DataOutputStream * outs) [static]
Definition at line 17 of file ConfigurationWriter.cpp.
References configurationFolder, configurationNumber, configurationString, ConfigurationFolder::getChild(), ConfigurationNode::getName(), ConfigurationNode::getType(), ConfigurationNumber::getValue(), ConfigurationFolder::numberOfChildren(), startNewLine(), and FilesystemUtils::writeLineToStream().
Referenced by ConfigurationInstance::writeToPath().
void ConfigurationWriter::startNewLine (unsigned int depth, DataOutputStream * outs) [static, private]
Definition at line 8 of file ConfigurationWriter.cpp.
References FilesystemUtils::writeLineToStream().
Referenced by outputNode().
The documentation for this class was generated from the following files:
Code/Configure/ConfigurationWriter.h
Code/Configure/ConfigurationWriter.cpp