Virtus: InterfaceLayer Class Reference
InterfaceLayer Class Reference
#include <InterfaceLayer.h>
Public Member Functions
InterfaceLayer ()
void draw (GRenderer *, int width, int height)
int getID ()
void AddElement (IElement *E)
void RemoveElement (IElement *E)
void drawText (int PointSize, int x, int y, std::string Text, FREngine *Renderer)
void drawQuad (float x, float y, float w, float h)
void drawQuadWithUIElement (float x, float y, float w, float h, unsigned int element_x, unsigned int element_y)
bool processEvent (Input_Event E)
FREngine * getDefaultTextRenderer ()
Private Attributes
FREngine m_defaultTextRenderer
std::vector< IElement * > m_interfaceElements
Texture * m_interfaceTex
VertexSet * m_quadVertexSet
Detailed Description
Definition at line 12 of file InterfaceLayer.h.
Constructor & Destructor Documentation
InterfaceLayer::InterfaceLayer ()
Definition at line 6 of file InterfaceLayer.cpp.
References ctype_float_rgb, Filesystem::evaluateChild(), GRenderer::getGraphicsAPI(), GRenderer::getRenderer(), Filesystem::getRoot(), TextureMonitor::getTexture(), GRenderer::getTextureMonitor(), FREngine::Load(), m_defaultTextRenderer, m_interfaceTex, m_quadVertexSet, GraphicsAPI::newVertexSet(), VertexSet::setColourValues(), VertexSet::setTextureCoordinates(), and VertexSet::setVertices().
Member Function Documentation
void InterfaceLayer::AddElement (IElement * E) [inline]
Definition at line 33 of file InterfaceLayer.h.
References m_interfaceElements.
Referenced by ModelViewer::onLoad().
void InterfaceLayer::draw (GRenderer * , int width, int height) [virtual]
Reimplemented from GRenderLayer.
Definition at line 45 of file InterfaceLayer.cpp.
References GRenderer::getGraphicsAPI(), GRenderer::getRenderer(), m_interfaceElements, and GraphicsAPI::setupFor2D().
void InterfaceLayer::drawQuad (float x, float y, float w, float h)
Definition at line 73 of file InterfaceLayer.cpp.
References VertexSet::Draw(), VertexSet::getTextureCoordinates(), VertexSet::getVertices(), m_quadVertexSet, and QUADS.
void InterfaceLayer::drawQuadWithUIElement (float x, float y, float w, float h, unsigned int element_x, unsigned int element_y)
Definition at line 98 of file InterfaceLayer.cpp.
References VertexSet::Draw(), Texture::getHeight(), VertexSet::getTextureCoordinates(), VertexSet::getVertices(), Texture::getWidth(), m_interfaceTex, m_quadVertexSet, Texture::makeActive(), and QUADS.
Referenced by IElements::Checkbox::draw(), and IElements::Button::draw().
void InterfaceLayer::drawText (int PointSize, int x, int y, std::string Text, FREngine * Renderer)
Definition at line 59 of file InterfaceLayer.cpp.
References m_defaultTextRenderer, and FREngine::Render().
Referenced by IElements::StaticText::draw().
FREngine* InterfaceLayer::getDefaultTextRenderer () [inline]
Definition at line 63 of file InterfaceLayer.h.
References m_defaultTextRenderer.
Referenced by IElements::Button::draw(), ViewerUserInterface::draw(), and GEngine::initialize().
int InterfaceLayer::getID () [inline, virtual]
Reimplemented from GRenderLayer.
Definition at line 28 of file InterfaceLayer.h.
References Layer_Interface.
bool InterfaceLayer::processEvent (Input_Event E)
Definition at line 151 of file InterfaceLayer.cpp.
References m_interfaceElements.
void InterfaceLayer::RemoveElement (IElement * E) [inline]
Definition at line 38 of file InterfaceLayer.h.
References m_interfaceElements.
Referenced by ModelViewer::onUnload().
Member Data Documentation
FREngine InterfaceLayer::m_defaultTextRenderer [private]
Definition at line 15 of file InterfaceLayer.h.
Referenced by drawText(), getDefaultTextRenderer(), and InterfaceLayer().
std::vector<IElement*> InterfaceLayer::m_interfaceElements [private]
Definition at line 16 of file InterfaceLayer.h.
Referenced by AddElement(), draw(), processEvent(), and RemoveElement().
Texture* InterfaceLayer::m_interfaceTex [private]
Definition at line 17 of file InterfaceLayer.h.
Referenced by drawQuadWithUIElement(), and InterfaceLayer().
VertexSet* InterfaceLayer::m_quadVertexSet [private]
Definition at line 20 of file InterfaceLayer.h.
Referenced by drawQuad(), drawQuadWithUIElement(), and InterfaceLayer().
The documentation for this class was generated from the following files:
Code/Render/Interface/InterfaceLayer.h
Code/Render/Interface/InterfaceLayer.cpp