Virtus: LocalFolder Class Reference
LocalFolder Class Reference
#include <LocalFolder.h>
Public Member Functions
LocalFolder (string Name, string Path)
~LocalFolder ()
unsigned int numChildren ()
FilesystemNode * getChild (unsigned int n)
File * newChild (string filename)
Folder * newChildFolder (string Name)
void refresh ()
string getName ()
FilesystemNode * searchForChild (std::string Name)
Private Member Functions
void emptyList ()
Private Attributes
string m_localFolderPath
string m_localName
std::vector< FilesystemNode * > m_entryList
Static Private Attributes
static const char * TAG = "Local Folder"
Detailed Description
Definition at line 8 of file LocalFolder.h.
Constructor & Destructor Documentation
LocalFolder::LocalFolder (string Name, string Path)
Definition at line 11 of file LocalFolder.cpp.
References m_localFolderPath, and m_localName.
Referenced by newChildFolder(), and refresh().
LocalFolder::~LocalFolder ()
Definition at line 16 of file LocalFolder.cpp.
References emptyList().
Member Function Documentation
void LocalFolder::emptyList () [private]
Definition at line 142 of file LocalFolder.cpp.
References m_entryList.
Referenced by refresh(), and ~LocalFolder().
FilesystemNode * LocalFolder::getChild (unsigned int n) [virtual]
Implements Folder.
Definition at line 29 of file LocalFolder.cpp.
References m_entryList.
string LocalFolder::getName () [inline, virtual]
Implements FilesystemNode.
Definition at line 32 of file LocalFolder.h.
File * LocalFolder::newChild (string filename) [virtual]
Implements Folder.
Definition at line 36 of file LocalFolder.cpp.
References m_entryList, m_localFolderPath, and searchForChild().
Folder * LocalFolder::newChildFolder (string Name) [virtual]
Implements Folder.
Definition at line 57 of file LocalFolder.cpp.
References LocalFolder(), m_entryList, m_localFolderPath, Folder::refresh(), and searchForChild().
unsigned int LocalFolder::numChildren () [virtual]
Implements Folder.
Definition at line 23 of file LocalFolder.cpp.
References m_entryList.
void LocalFolder::refresh () [virtual]
Implements Folder.
Definition at line 83 of file LocalFolder.cpp.
References emptyList(), LocalFolder(), m_entryList, m_localFolderPath, and Folder::refresh().
FilesystemNode * LocalFolder::searchForChild (std::string Name)
Definition at line 152 of file LocalFolder.cpp.
References GEngine::getInstance(), GEngine::getLog(), m_entryList, TAG, and LogWriter::writeLine().
Referenced by newChild(), and newChildFolder().
Member Data Documentation
std::vector<FilesystemNode*> LocalFolder::m_entryList [private]
Definition at line 16 of file LocalFolder.h.
Referenced by emptyList(), getChild(), newChild(), newChildFolder(), numChildren(), refresh(), and searchForChild().
string LocalFolder::m_localFolderPath [private]
Definition at line 13 of file LocalFolder.h.
Referenced by LocalFolder(), newChild(), newChildFolder(), and refresh().
string LocalFolder::m_localName [private]
Definition at line 14 of file LocalFolder.h.
Referenced by LocalFolder().
const char * LocalFolder::TAG = "Local Folder" [static, private]
Definition at line 11 of file LocalFolder.h.
Referenced by searchForChild().
The documentation for this class was generated from the following files:
Code/Filesystem/LocalFolder.h
Code/Filesystem/LocalFolder.cpp