Virtus: ResourceMonitor Class Reference
ResourceMonitor Class Reference
#include <ResourceMonitor.h>
Public Member Functions
ResourceMonitor ()
virtual ~ResourceMonitor ()
Protected Member Functions
virtual void f_freeEntity (void *m_Entity)
virtual void * f_loadEntity (std::string Name)
void f_freeIndex (unsigned int i)
void f_addEntity (std::string Filename, void *Entity)
void * rmGetResource (std::string Resource)
void rmReleaseResource (void *Resource)
Protected Attributes
std::vector
< resource_monitor_entry > m_resourceList
Detailed Description
Definition at line 25 of file ResourceMonitor.h.
Constructor & Destructor Documentation
ResourceMonitor::ResourceMonitor ()
Definition at line 80 of file ResourceMonitor.cpp.
ResourceMonitor::~ResourceMonitor () [virtual]
Definition at line 85 of file ResourceMonitor.cpp.
Member Function Documentation
void ResourceMonitor::f_addEntity (std::string Filename, void * Entity) [protected]
Definition at line 30 of file ResourceMonitor.cpp.
References resource_monitor_entry::m_boundCount, resource_monitor_entry::m_Entity, m_resourceList, and resource_monitor_entry::m_ResourceName.
Referenced by TextureMonitor::f_loadEntity().
void ResourceMonitor::f_freeEntity (void * m_Entity) [protected, virtual]
Reimplemented in TextureMonitor.
Definition at line 4 of file ResourceMonitor.cpp.
Referenced by f_freeIndex().
void ResourceMonitor::f_freeIndex (unsigned int i) [protected]
Definition at line 14 of file ResourceMonitor.cpp.
References f_freeEntity(), resource_monitor_entry::m_Entity, and m_resourceList.
Referenced by rmReleaseResource().
void * ResourceMonitor::f_loadEntity (std::string Name) [protected, virtual]
Reimplemented in TextureMonitor.
Definition at line 9 of file ResourceMonitor.cpp.
Referenced by rmGetResource().
void * ResourceMonitor::rmGetResource (std::string Resource) [protected]
Definition at line 46 of file ResourceMonitor.cpp.
References f_loadEntity(), and m_resourceList.
Referenced by TextureMonitor::getTexture().
void ResourceMonitor::rmReleaseResource (void * Resource) [protected]
Definition at line 61 of file ResourceMonitor.cpp.
References f_freeIndex(), and m_resourceList.
Referenced by TextureMonitor::releaseTexture().
Member Data Documentation
std::vector<resource_monitor_entry> ResourceMonitor::m_resourceList [protected]
Definition at line 29 of file ResourceMonitor.h.
Referenced by f_addEntity(), f_freeIndex(), rmGetResource(), rmReleaseResource(), and TextureMonitor::~TextureMonitor().
The documentation for this class was generated from the following files:
Code/Render/ResourceMonitor/ResourceMonitor.h
Code/Render/ResourceMonitor/ResourceMonitor.cpp