Virtus: Button Class Reference
Button Class Reference
#include <Button.h>
Public Member Functions
Button (float x, float y, float w, float h, const char *BtnNormalText, const char *BtnOverText, const char *BtnDownText, Color textClr, Color bgNormal, Color mouseOver, Color mouseDown)
~Button ()
void draw (InterfaceLayer *IL)
bool handleInput (Input_Event e)
void setOnMouseUp (void(*onUpFn)(Button *Btn))
Protected Member Functions
virtual void onDown ()
void onUp ()
void handleButtonEvent (Input_Event e)
Protected Attributes
unsigned int m_textPointSize
Color m_textColour
Color m_normalBg
Color m_btnDownBg
Color m_mouseOverBg
bool m_mouseOverElement
bool m_mouseDownOverElement
void(* onUpFn)(Button *Btn)
char * m_buttonNormalText
char * m_mouseOverText
char * m_mouseDownText
Detailed Description
Definition at line 7 of file Button.h.
Constructor & Destructor Documentation
Button::Button (float x, float y, float w, float h, const char * BtnNormalText, const char * BtnOverText, const char * BtnDownText, Color textClr, Color bgNormal, Color mouseOver, Color mouseDown)
Definition at line 6 of file Button.cpp.
References m_btnDownBg, m_buttonNormalText, m_mouseDownOverElement, m_mouseDownText, m_mouseOverBg, m_mouseOverText, m_normalBg, m_textColour, and onUpFn.
Button::~Button ()
Definition at line 27 of file Button.cpp.
References m_buttonNormalText, m_mouseDownText, and m_mouseOverText.
Member Function Documentation
void Button::draw (InterfaceLayer * IL) [virtual]
Implements IElement.
Definition at line 36 of file Button.cpp.
References GraphicsAPI::disableBlending(), InterfaceLayer::drawQuadWithUIElement(), GraphicsAPI::enableBlending(), InterfaceLayer::getDefaultTextRenderer(), GRenderer::getGraphicsAPI(), GRenderer::getRenderer(), IElement::height, m_btnDownBg, m_buttonNormalText, m_mouseDownOverElement, m_mouseDownText, m_mouseOverBg, m_mouseOverElement, m_mouseOverText, m_normalBg, FREngine::Render(), IElement::width, IElement::x, and IElement::y.
void Button::handleButtonEvent (Input_Event e) [protected]
Definition at line 101 of file Button.cpp.
References Input_Event::Event_Data, m_mouseDownOverElement, m_mouseOverElement, MOUSE_DOWN, MOUSE_MOTION, MOUSE_UP, onDown(), and onUp().
Referenced by handleInput().
bool Button::handleInput (Input_Event e) [virtual]
Implements IElement.
Definition at line 145 of file Button.cpp.
References Input_Event::Event_Data, Input_Event::Event_ID, handleButtonEvent(), IElement::height, input_event_button_one, m_mouseDownOverElement, m_mouseOverElement, IElement::width, IElement::x, and IElement::y.
virtual void Button::onDown () [inline, protected, virtual]
Definition at line 22 of file Button.h.
Referenced by handleButtonEvent().
void Button::onUp () [protected]
Definition at line 137 of file Button.cpp.
References onUpFn.
Referenced by handleButtonEvent().
void Button::setOnMouseUp (void(*)(Button *Btn) onUpFn)
Definition at line 132 of file Button.cpp.
References onUpFn.
Referenced by ModelViewer::onLoad().
Member Data Documentation
Color Button::m_btnDownBg [protected]
Definition at line 14 of file Button.h.
Referenced by Button(), and draw().
char* Button::m_buttonNormalText [protected]
Definition at line 27 of file Button.h.
Referenced by Button(), draw(), and ~Button().
bool Button::m_mouseDownOverElement [protected]
Definition at line 18 of file Button.h.
Referenced by Button(), draw(), handleButtonEvent(), and handleInput().
char* Button::m_mouseDownText [protected]
Definition at line 29 of file Button.h.
Referenced by Button(), draw(), and ~Button().
Color Button::m_mouseOverBg [protected]
Definition at line 15 of file Button.h.
Referenced by Button(), and draw().
bool Button::m_mouseOverElement [protected]
Definition at line 17 of file Button.h.
Referenced by draw(), handleButtonEvent(), and handleInput().
char* Button::m_mouseOverText [protected]
Definition at line 28 of file Button.h.
Referenced by Button(), draw(), and ~Button().
Color Button::m_normalBg [protected]
Definition at line 13 of file Button.h.
Referenced by Button(), and draw().
Color Button::m_textColour [protected]
Definition at line 12 of file Button.h.
Referenced by Button().
unsigned int Button::m_textPointSize [protected]
Definition at line 11 of file Button.h.
void(* Button::onUpFn)(Button *Btn) [protected]
Definition at line 20 of file Button.h.
Referenced by Button(), onUp(), and setOnMouseUp().
The documentation for this class was generated from the following files:
Code/Render/Interface/Button.h
Code/Render/Interface/Button.cpp