Virtus: Vector2f Class Reference
Vector2f Class Reference
A vector with 2 points.
#include <Vector.h>
Public Member Functions
Vector2f ()
float length ()
Vector2f scale (float time_milis)
Vector2f normalize ()
Vector2f add (Vector2f vector)
Vector2f subtract (Vector2f vector)
Vector2f negative ()
Vector2f multiply (float f)
Vector2f divide (float f)
Vector2f reflect (Vector2f other)
float dotProduct (Vector2f vector)
float angle (Vector2f vector)
Public Attributes
float x
float y
Private Attributes
float m_Length
bool m_Dirty
Detailed Description
A vector with 2 points.
Definition at line 8 of file Vector.h.
Constructor & Destructor Documentation
Vector2f::Vector2f ()
Definition at line 4 of file Vector.cpp.
References m_Dirty, x, and y.
Member Function Documentation
Vector2f Vector2f::add (Vector2f vector)
Definition at line 58 of file Vector.cpp.
References x, and y.
float Vector2f::angle (Vector2f vector)
Definition at line 94 of file Vector.cpp.
References dotProduct(), and normalize().
Vector2f Vector2f::divide (float f)
Definition at line 112 of file Vector.cpp.
References x, and y.
float Vector2f::dotProduct (Vector2f vector)
Definition at line 87 of file Vector.cpp.
References x, and y.
Referenced by angle(), and reflect().
float Vector2f::length ()
Definition at line 18 of file Vector.cpp.
References m_Dirty, m_Length, x, and y.
Referenced by normalize().
Vector2f Vector2f::multiply (float f)
Definition at line 102 of file Vector.cpp.
References x, and y.
Referenced by reflect().
Vector2f Vector2f::negative ()
Definition at line 68 of file Vector.cpp.
References x, and y.
Vector2f Vector2f::normalize ()
Definition at line 38 of file Vector.cpp.
References length(), x, and y.
Referenced by angle().
Vector2f Vector2f::reflect (Vector2f other)
Definition at line 11 of file Vector.cpp.
References dotProduct(), multiply(), and subtract().
Vector2f Vector2f::scale (float time_milis)
Definition at line 48 of file Vector.cpp.
References x, and y.
Vector2f Vector2f::subtract (Vector2f vector)
Definition at line 78 of file Vector.cpp.
References x, and y.
Referenced by reflect().
Member Data Documentation
bool Vector2f::m_Dirty [private]
Definition at line 11 of file Vector.h.
Referenced by length(), and Vector2f().
float Vector2f::m_Length [private]
Definition at line 10 of file Vector.h.
Referenced by length().
float Vector2f::x
Definition at line 16 of file Vector.h.
Referenced by add(), divide(), dotProduct(), length(), multiply(), negative(), normalize(), scale(), subtract(), and Vector2f().
float Vector2f::y
Definition at line 16 of file Vector.h.
Referenced by add(), divide(), dotProduct(), length(), multiply(), negative(), normalize(), scale(), subtract(), and Vector2f().
The documentation for this class was generated from the following files:
Code/Math/Vector.h
Code/Math/Vector.cpp