Virtus: ToggleWireframeHandler Class Reference
ToggleWireframeHandler Class Reference
#include <EventHandlers.h>
Private Member Functions
void triggerCallback (std::vector< int > I, int Flags)
Detailed Description
Definition at line 69 of file EventHandlers.h.
Member Function Documentation
void ToggleWireframeHandler::triggerCallback (std::vector< int > I, int Flags) [inline, private, virtual]
Reimplemented from EventCallback.
Definition at line 72 of file EventHandlers.h.
References GRenderer::getRenderer(), GRenderer::getRenderWireframeValue(), and GRenderer::setRenderWireframeValue().
The documentation for this class was generated from the following file:
Code/3DViewer/EventHandlers.h