Virtus: ConfigurationString Class Reference
ConfigurationString Class Reference
#include <ConfigurationString.h>
Public Member Functions
ConfigurationString (const char *name, const char *stringValue)
~ConfigurationString ()
int getType ()
const char * getStringData ()
void setStringData (const char *data)
Private Member Functions
void freeStringData ()
Private Attributes
char * m_stringData
Detailed Description
Definition at line 7 of file ConfigurationString.h.
Constructor & Destructor Documentation
ConfigurationString::ConfigurationString (const char * name, const char * stringValue)
Definition at line 26 of file ConfigurationString.cpp.
References m_stringData, and setStringData().
ConfigurationString::~ConfigurationString ()
Definition at line 35 of file ConfigurationString.cpp.
References freeStringData().
Member Function Documentation
void ConfigurationString::freeStringData () [private]
Definition at line 3 of file ConfigurationString.cpp.
References m_stringData.
Referenced by setStringData(), and ~ConfigurationString().
const char* ConfigurationString::getStringData () [inline]
Definition at line 23 of file ConfigurationString.h.
References m_stringData.
Referenced by GEngine::initialize().
int ConfigurationString::getType () [inline, virtual]
Reimplemented from ConfigurationNode.
Definition at line 20 of file ConfigurationString.h.
References configurationString.
void ConfigurationString::setStringData (const char * data)
Definition at line 15 of file ConfigurationString.cpp.
References freeStringData(), and m_stringData.
Referenced by ConfigurationString().
Member Data Documentation
char* ConfigurationString::m_stringData [private]
Definition at line 11 of file ConfigurationString.h.
Referenced by ConfigurationString(), freeStringData(), getStringData(), and setStringData().
The documentation for this class was generated from the following files:
Code/Configure/ConfigurationString.h
Code/Configure/ConfigurationString.cpp