Virtus: BeeHive Class Reference
BeeHive Class Reference
Manages a collection of worker bees which process jobs passed to them over multiple threads.
#include <Hive.h>
Public Member Functions
BeeHive (unsigned int numberOfBees)
~BeeHive ()
void issueOrders (WorkerJob *Job)
WorkerJob * beeRequestNextJob ()
bool allIdle ()
Private Attributes
WorkerBee ** m_bees
unsigned int m_numberOfBees
std::queue< WorkerJob * > m_waitingJobs
Mutex jobQueueMutex
Detailed Description
Manages a collection of worker bees which process jobs passed to them over multiple threads.
Definition at line 14 of file Hive.h.
Constructor & Destructor Documentation
BeeHive::BeeHive (unsigned int numberOfBees)
Definition at line 6 of file Hive.cpp.
References GEngine::getInstance(), GEngine::getLog(), m_bees, m_numberOfBees, Thread::start(), and LogWriter::writeData().
BeeHive::~BeeHive ()
Definition at line 29 of file Hive.cpp.
References GEngine::getInstance(), GEngine::getLog(), m_bees, m_numberOfBees, and LogWriter::writeData().
Member Function Documentation
bool BeeHive::allIdle ()
Definition at line 48 of file Hive.cpp.
References jobQueueMutex, Mutex::Lock(), m_bees, m_numberOfBees, m_waitingJobs, and Mutex::Unlock().
WorkerJob * BeeHive::beeRequestNextJob ()
Definition at line 96 of file Hive.cpp.
References jobQueueMutex, Mutex::Lock(), m_waitingJobs, and Mutex::Unlock().
Referenced by WorkerBee::run().
void BeeHive::issueOrders (WorkerJob * Job)
Definition at line 82 of file Hive.cpp.
References jobQueueMutex, Mutex::Lock(), m_waitingJobs, and Mutex::Unlock().
Member Data Documentation
Mutex BeeHive::jobQueueMutex [private]
Definition at line 21 of file Hive.h.
Referenced by allIdle(), beeRequestNextJob(), and issueOrders().
WorkerBee** BeeHive::m_bees [private]
Definition at line 17 of file Hive.h.
Referenced by allIdle(), BeeHive(), and ~BeeHive().
unsigned int BeeHive::m_numberOfBees [private]
Definition at line 18 of file Hive.h.
Referenced by allIdle(), BeeHive(), and ~BeeHive().
std::queue<WorkerJob*> BeeHive::m_waitingJobs [private]
Definition at line 20 of file Hive.h.
Referenced by allIdle(), beeRequestNextJob(), and issueOrders().
The documentation for this class was generated from the following files:
Code/HIVE/Hive.h
Code/HIVE/Hive.cpp