Virtus: GraphicsAPI Class Reference
GraphicsAPI Class Reference
#include <GraphicsAPI.h>
Public Member Functions
virtual ~GraphicsAPI ()
virtual RenderWindow * getRenderWindow ()=0
virtual VertexSet * newVertexSet ()=0
virtual const char * getAPISummary ()=0
virtual Texture * newTexture ()=0
virtual ShaderFactory * getShaderFactory ()=0
virtual void clearScreen ()=0
virtual bool initialize ()=0
virtual void setupFor3D (unsigned int width, unsigned int height)=0
virtual void setupFor2D (unsigned int width, unsigned int height)=0
virtual void pushMatrix ()=0
virtual void popMatrix ()=0
virtual void resetMatrix ()=0
virtual void translateMatrix (float x, float y, float z)=0
virtual void rotateMatrix (float x, float y, float z)=0
virtual void enableBlending ()=0
virtual void disableBlending ()=0
virtual void setWireframeRender (bool val)=0
virtual void clearActiveTexture ()=0
virtual void setDepthTesting (bool value)=0
virtual void setupViewport (unsigned int start_x, unsigned int start_y, unsigned int end_x, unsigned int end_y)=0
virtual void clearErrors ()=0
virtual bool setupRenderToTextureTextures (unsigned int w, unsigned int h, Texture *colour, Texture *depth)=0
virtual bool setRenderToTexture (unsigned int width, unsigned int height, Texture *tex, Texture *depth)=0
Static Public Member Functions
static GraphicsAPI * getAPIInstance (const char *Name)
Detailed Description
Definition at line 9 of file GraphicsAPI.h.
Constructor & Destructor Documentation
virtual GraphicsAPI::~GraphicsAPI () [inline, virtual]
Definition at line 14 of file GraphicsAPI.h.
Member Function Documentation
virtual void GraphicsAPI::clearActiveTexture () [pure virtual]
Implemented in GL2GraphicsAPI.
Referenced by Plane::draw(), and GRenderer::renderScene().
virtual void GraphicsAPI::clearErrors () [pure virtual]
Implemented in GL2GraphicsAPI.
Referenced by GRenderer::end().
virtual void GraphicsAPI::clearScreen () [pure virtual]
Implemented in GL2GraphicsAPI.
Referenced by GRenderer::begin().
virtual void GraphicsAPI::disableBlending () [pure virtual]
Implemented in GL2GraphicsAPI.
Referenced by Checkbox::draw(), Button::draw(), ViewerUserInterface::draw(), and GRenderer::renderScene().
virtual void GraphicsAPI::enableBlending () [pure virtual]
Implemented in GL2GraphicsAPI.
Referenced by Checkbox::draw(), Button::draw(), ViewerUserInterface::draw(), and GRenderer::renderScene().
GraphicsAPI * GraphicsAPI::getAPIInstance (const char * Name) [static]
Definition at line 6 of file GraphicsAPI.cpp.
Referenced by GRenderer::initialize().
virtual const char* GraphicsAPI::getAPISummary () [pure virtual]
Implemented in GL2GraphicsAPI.
Referenced by GRenderer::initialize().
virtual RenderWindow* GraphicsAPI::getRenderWindow () [pure virtual]
Implemented in GL2GraphicsAPI.
Referenced by GRenderer::begin(), GRenderer::getWindow(), and GRenderer::initialize().
virtual ShaderFactory* GraphicsAPI::getShaderFactory () [pure virtual]
Implemented in GL2GraphicsAPI.
Referenced by TerrainNode::TerrainNode(), and TestNode::TestNode().
virtual bool GraphicsAPI::initialize () [pure virtual]
Implemented in GL2GraphicsAPI.
Referenced by GRenderer::initialize().
virtual Texture* GraphicsAPI::newTexture () [pure virtual]
Implemented in GL2GraphicsAPI.
Referenced by TextureMonitor::f_loadEntity(), FREngine::LoadFontmap(), and TerrainNode::TerrainNode().
virtual VertexSet* GraphicsAPI::newVertexSet () [pure virtual]
Implemented in GL2GraphicsAPI.
Referenced by FontMap::FontMap(), TerrainPatch::generateDrawLOD(), InterfaceLayer::InterfaceLayer(), Plane::Plane(), TestNode::TestNode(), and WorldNode::WorldNode().
virtual void GraphicsAPI::popMatrix () [pure virtual]
Implemented in GL2GraphicsAPI.
Referenced by WorldNode::draw(), TestNode::draw(), TerrainNode::draw(), and Plane::draw().
virtual void GraphicsAPI::pushMatrix () [pure virtual]
Implemented in GL2GraphicsAPI.
Referenced by WorldNode::draw(), TestNode::draw(), TerrainNode::draw(), and Plane::draw().
virtual void GraphicsAPI::resetMatrix () [pure virtual]
Implemented in GL2GraphicsAPI.
Referenced by WorldNode::draw(), and ThreeDRenderLayer::draw().
virtual void GraphicsAPI::rotateMatrix (float x, float y, float z) [pure virtual]
Implemented in GL2GraphicsAPI.
Referenced by WorldNode::draw(), TestNode::draw(), TerrainNode::draw(), and Camera::renderMoveTo().
virtual void GraphicsAPI::setDepthTesting (bool value) [pure virtual]
Implemented in GL2GraphicsAPI.
Referenced by WorldNode::draw().
virtual bool GraphicsAPI::setRenderToTexture (unsigned int width, unsigned int height, Texture * tex, Texture * depth) [pure virtual]
Implemented in GL2GraphicsAPI.
virtual void GraphicsAPI::setupFor2D (unsigned int width, unsigned int height) [pure virtual]
Implemented in GL2GraphicsAPI.
Referenced by InterfaceLayer::draw(), and GRenderer::renderScene().
virtual void GraphicsAPI::setupFor3D (unsigned int width, unsigned int height) [pure virtual]
Implemented in GL2GraphicsAPI.
Referenced by ThreeDRenderLayer::draw().
virtual bool GraphicsAPI::setupRenderToTextureTextures (unsigned int w, unsigned int h, Texture * colour, Texture * depth) [pure virtual]
Implemented in GL2GraphicsAPI.
virtual void GraphicsAPI::setupViewport (unsigned int start_x, unsigned int start_y, unsigned int end_x, unsigned int end_y) [pure virtual]
Implemented in GL2GraphicsAPI.
Referenced by GRenderer::begin().
virtual void GraphicsAPI::setWireframeRender (bool val) [pure virtual]
Implemented in GL2GraphicsAPI.
Referenced by ThreeDRenderLayer::draw().
virtual void GraphicsAPI::translateMatrix (float x, float y, float z) [pure virtual]
Implemented in GL2GraphicsAPI.
Referenced by WorldNode::draw(), TestNode::draw(), TerrainNode::draw(), and Camera::renderMoveTo().
The documentation for this class was generated from the following files:
Code/Render/GraphicsAPI/GraphicsAPI.h
Code/Render/GraphicsAPI/GraphicsAPI.cpp