Virtus: Thread Class Reference
Thread Class Reference
An abstraction of a thread.
#include <Thread.h>
Public Member Functions
Thread ()
virtual ~Thread ()
void start (void *Arg)
bool running ()
Protected Member Functions
void enter ()
virtual void run (void *Arg)=0
Static Private Member Functions
static void entryPoint (void *thread)
Private Attributes
void * m_threadArg
bool m_startedThread
Detailed Description
An abstraction of a thread.
Definition at line 18 of file Thread.h.
Constructor & Destructor Documentation
Thread::Thread ()
Definition at line 3 of file Thread.cpp.
References m_startedThread, and m_threadArg.
Thread::~Thread () [virtual]
Definition at line 9 of file Thread.cpp.
Member Function Documentation
void Thread::enter () [protected]
Definition at line 25 of file Thread.cpp.
References m_threadArg, and run().
Referenced by entryPoint().
void Thread::entryPoint (void * thread) [static, private]
Definition at line 30 of file Thread.cpp.
References enter().
Referenced by start().
virtual void Thread::run (void * Arg) [protected, pure virtual]
Implemented in WorkerBee.
Referenced by enter().
bool Thread::running () [inline]
Definition at line 42 of file Thread.h.
References m_startedThread.
void Thread::start (void * Arg)
Definition at line 14 of file Thread.cpp.
References entryPoint(), and m_threadArg.
Referenced by BeeHive::BeeHive().
Member Data Documentation
bool Thread::m_startedThread [private]
Definition at line 29 of file Thread.h.
Referenced by running(), and Thread().
void* Thread::m_threadArg [private]
Definition at line 28 of file Thread.h.
Referenced by enter(), start(), and Thread().
The documentation for this class was generated from the following files:
Code/HIVE/Thread.h
Code/HIVE/Thread.cpp