Virtus: LocalDataInputStream Class Reference
LocalDataInputStream Class Reference
#include <LocalInputStream.h>
Public Member Functions
LocalDataInputStream (const char *filePath)
~LocalDataInputStream ()
bool read (void *target, unsigned long amount)
void close ()
bool open (bool textMode)
bool isOpen ()
bool skip (unsigned long bytes)
bool rewind (unsigned long bytes)
Private Attributes
char * m_localDataFilePath
FILE * m_fileInputStream
Detailed Description
Definition at line 7 of file LocalInputStream.h.
Constructor & Destructor Documentation
LocalDataInputStream::LocalDataInputStream (const char * filePath)
Definition at line 3 of file LocalInputStream.cpp.
References m_fileInputStream, and m_localDataFilePath.
LocalDataInputStream::~LocalDataInputStream ()
Definition at line 13 of file LocalInputStream.cpp.
References close(), isOpen(), and m_localDataFilePath.
Member Function Documentation
void LocalDataInputStream::close () [virtual]
Implements DataInputStream.
Definition at line 48 of file LocalInputStream.cpp.
References isOpen(), and m_fileInputStream.
Referenced by ~LocalDataInputStream().
bool LocalDataInputStream::isOpen () [virtual]
Implements DataInputStream.
Definition at line 80 of file LocalInputStream.cpp.
References m_fileInputStream.
Referenced by close(), open(), read(), rewind(), skip(), and ~LocalDataInputStream().
bool LocalDataInputStream::open (bool textMode) [virtual]
Implements DataInputStream.
Definition at line 61 of file LocalInputStream.cpp.
References isOpen(), m_fileInputStream, and m_localDataFilePath.
bool LocalDataInputStream::read (void * target, unsigned long amount) [virtual]
Implements DataInputStream.
Definition at line 31 of file LocalInputStream.cpp.
References isOpen(), and m_fileInputStream.
bool LocalDataInputStream::rewind (unsigned long bytes) [virtual]
Implements DataInputStream.
Definition at line 109 of file LocalInputStream.cpp.
References isOpen(), and m_fileInputStream.
bool LocalDataInputStream::skip (unsigned long bytes) [virtual]
Implements DataInputStream.
Definition at line 93 of file LocalInputStream.cpp.
References isOpen(), and m_fileInputStream.
Member Data Documentation
FILE* LocalDataInputStream::m_fileInputStream [private]
Definition at line 11 of file LocalInputStream.h.
Referenced by close(), isOpen(), LocalDataInputStream(), open(), read(), rewind(), and skip().
char* LocalDataInputStream::m_localDataFilePath [private]
Definition at line 10 of file LocalInputStream.h.
Referenced by LocalDataInputStream(), open(), and ~LocalDataInputStream().
The documentation for this class was generated from the following files:
Code/Filesystem/LocalInputStream.h
Code/Filesystem/LocalInputStream.cpp