Virtus: GLShaderFactory Class Reference
GLShaderFactory Class Reference
#include <GLShaderFactory.h>
Public Member Functions
int readFragmentShaderSourceFromFile (const char *Filename, char *readBuffer, unsigned int maxReadLength)
int readVertexShaderSourceFromFile (const char *Filename, char *readBuffer, unsigned int maxReadLength)
Shader * loadShader (File *inputFile)
Detailed Description
Definition at line 5 of file GLShaderFactory.h.
Member Function Documentation
Shader * GLShaderFactory::loadShader (File * inputFile) [virtual]
Implements ShaderFactory.
Definition at line 142 of file GLShaderFactory.cpp.
References File::createInputStream(), fileId, File::getType(), File::length(), GLShader::loadShader(), nextWord(), DataInputStream::open(), and DataInputStream::read().
int GLShaderFactory::readFragmentShaderSourceFromFile (const char * Filename, char * readBuffer, unsigned int maxReadLength)
Definition at line 7 of file GLShaderFactory.cpp.
int GLShaderFactory::readVertexShaderSourceFromFile (const char * Filename, char * readBuffer, unsigned int maxReadLength)
Definition at line 32 of file GLShaderFactory.cpp.
The documentation for this class was generated from the following files:
Code/Render/GraphicsAPI/GL2/GLShaderFactory.h
Code/Render/GraphicsAPI/GL2/GLShaderFactory.cpp