Virtus: Plane Class Reference
Plane Class Reference
#include <Plane.h>
Public Member Functions
Plane (float sx, float sy, float ex, float ey)
~Plane ()
void draw (Camera *cam)
Private Attributes
VertexSet * m_planeVSet
Detailed Description
Definition at line 6 of file Plane.h.
Constructor & Destructor Documentation
Plane::Plane (float sx, float sy, float ex, float ey)
Definition at line 4 of file Plane.cpp.
References ctype_float_rgba, GRenderer::getGraphicsAPI(), GRenderer::getRenderer(), m_planeVSet, GraphicsAPI::newVertexSet(), VertexSet::setColourValues(), and VertexSet::setVertices().
Plane::~Plane ()
Definition at line 28 of file Plane.cpp.
Member Function Documentation
void Plane::draw (Camera * cam) [virtual]
Reimplemented from SceneNode.
Definition at line 33 of file Plane.cpp.
References GraphicsAPI::clearActiveTexture(), VertexSet::Draw(), GRenderer::getGraphicsAPI(), GRenderer::getRenderer(), m_planeVSet, GraphicsAPI::popMatrix(), GraphicsAPI::pushMatrix(), and QUADS.
Member Data Documentation
VertexSet* Plane::m_planeVSet [private]
Definition at line 9 of file Plane.h.
Referenced by draw(), and Plane().
The documentation for this class was generated from the following files:
Code/Render/3D/Plane.h
Code/Render/3D/Plane.cpp