Virtus: Vector3f Class Reference
Vector3f Class Reference
A vector with 3 points.
#include <Vector.h>
Public Member Functions
Vector3f ()
Initialize a blank vector(0, 0, 0)
Vector3f (float x, float y, float z)
Initialize a new vector with the specified values.
Vector3f (float *matrix)
Initialize a vector from the specified float array.
void setX (float x)
Set the X value.
void setY (float y)
Set the Y value.
void setZ (float z)
Set the Z value.
void setMatrix (float *newMatrix)
Set the values to values on the specified float array.
float getX ()
Return the X value of the vector.
float getY ()
Return the Y value of the vector.
float getZ ()
Get the Z value of the vector.
float * getMatrix ()
Get a reference to the raw array.
float length ()
Calculate the length of the vector.
Vector3f normalize ()
Return a new vector containing the normalization of this one.
Vector3f cross (Vector3f other)
Return the cross product of this vector with another.
Private Attributes
float m_storeLength
bool m_lengthDirty
float m_vectorMatrix [3]
Detailed Description
A vector with 3 points.
Definition at line 41 of file Vector.h.
Constructor & Destructor Documentation
Vector3f::Vector3f ()
Initialize a blank vector(0, 0, 0)
Definition at line 137 of file Vector.cpp.
References m_lengthDirty, m_storeLength, and m_vectorMatrix.
Referenced by cross().
Vector3f::Vector3f (float x, float y, float z)
Initialize a new vector with the specified values.
Definition at line 122 of file Vector.cpp.
References m_lengthDirty, setX(), setY(), and setZ().
Vector3f::Vector3f (float * matrix)
Initialize a vector from the specified float array.
Definition at line 132 of file Vector.cpp.
References setMatrix().
Member Function Documentation
Vector3f Vector3f::cross (Vector3f other)
Return the cross product of this vector with another.
Definition at line 169 of file Vector.cpp.
References getX(), getY(), getZ(), and Vector3f().
float * Vector3f::getMatrix ()
Get a reference to the raw array.
Definition at line 223 of file Vector.cpp.
References m_vectorMatrix.
Referenced by WorldNode::draw(), Camera::move(), Camera::renderMoveTo(), and Camera::rotate().
float Vector3f::getX ()
Return the X value of the vector.
Definition at line 208 of file Vector.cpp.
References m_vectorMatrix.
Referenced by cross(), TestNode::draw(), TerrainNode::draw(), TerrainNode::recalculateLightMaps(), and ModelViewer::updateApplication().
float Vector3f::getY ()
Return the Y value of the vector.
Definition at line 213 of file Vector.cpp.
References m_vectorMatrix.
Referenced by cross(), TestNode::draw(), TerrainNode::draw(), and ModelViewer::updateApplication().
float Vector3f::getZ ()
Get the Z value of the vector.
Definition at line 218 of file Vector.cpp.
References m_vectorMatrix.
Referenced by cross(), TestNode::draw(), TerrainNode::draw(), and TerrainNode::recalculateLightMaps().
float Vector3f::length ()
Calculate the length of the vector.
Definition at line 147 of file Vector.cpp.
References m_lengthDirty, m_storeLength, and m_vectorMatrix.
Referenced by normalize().
Vector3f Vector3f::normalize ()
Return a new vector containing the normalization of this one.
Definition at line 163 of file Vector.cpp.
References length(), and m_vectorMatrix.
Referenced by TerrainNode::recalculateLightMaps().
void Vector3f::setMatrix (float * newMatrix)
Set the values to values on the specified float array.
Definition at line 199 of file Vector.cpp.
References m_lengthDirty, and m_vectorMatrix.
Referenced by Camera::Camera(), Camera::move(), Camera::rotate(), Camera::setPosition(), Camera::setRotation(), and Vector3f().
void Vector3f::setX (float x)
Set the X value.
Definition at line 181 of file Vector.cpp.
References m_lengthDirty, and m_vectorMatrix.
Referenced by ModelViewer::onLoad(), TerrainNode::recalculateLightMaps(), and Vector3f().
void Vector3f::setY (float y)
Set the Y value.
Definition at line 187 of file Vector.cpp.
References m_lengthDirty, and m_vectorMatrix.
Referenced by ModelViewer::onLoad(), TerrainNode::recalculateLightMaps(), and Vector3f().
void Vector3f::setZ (float z)
Set the Z value.
Definition at line 193 of file Vector.cpp.
References m_lengthDirty, and m_vectorMatrix.
Referenced by ModelViewer::onLoad(), TerrainNode::recalculateLightMaps(), and Vector3f().
Member Data Documentation
bool Vector3f::m_lengthDirty [private]
Definition at line 45 of file Vector.h.
Referenced by length(), setMatrix(), setX(), setY(), setZ(), and Vector3f().
float Vector3f::m_storeLength [private]
Definition at line 44 of file Vector.h.
Referenced by length(), and Vector3f().
float Vector3f::m_vectorMatrix[3] [private]
Definition at line 47 of file Vector.h.
Referenced by getMatrix(), getX(), getY(), getZ(), length(), normalize(), setMatrix(), setX(), setY(), setZ(), and Vector3f().
The documentation for this class was generated from the following files:
Code/Math/Vector.h
Code/Math/Vector.cpp