Virtus: Code/entry.cpp File Reference
Code/entry.cpp File Reference
#include <Core/GEngine.h>
#include <3DViewer/ViewerApplication.h>
Functions
int main ()
Entry point of the program, loads the base application and starts the engine loop.
Function Documentation
int main ()
Entry point of the program, loads the base application and starts the engine loop.
Definition at line 9 of file entry.cpp.
References GEngine::errorDetails(), GEngine::gameLoop(), GEngine::getInstance(), GRenderer::getRenderer(), GEngine::isInErrorState(), GEngine::loadApplication(), and GEngine::unloadApplication().