Virtus: Code/Render/GraphicsAPI/GL2/GLShaderFactory.cpp File Reference
Code/Render/GraphicsAPI/GL2/GLShaderFactory.cpp File Reference
#include "GLShaderFactory.h"
#include <stdio.h>
#include <string.h>
#include <ctype.h>
#include "GLShader.h"
Functions
void skipWhitespace (const char *inputData, size_t *cPtr)
bool nextWord (const char *inputData, size_t *cPtr, char *wordBuffer)
Function Documentation
bool nextWord (const char * inputData, size_t * cPtr, char * wordBuffer)
Definition at line 86 of file GLShaderFactory.cpp.
References skipWhitespace().
Referenced by GLShaderFactory::loadShader().
void skipWhitespace (const char * inputData, size_t * cPtr)
Definition at line 58 of file GLShaderFactory.cpp.
Referenced by nextWord().