Virtus: Code/3DViewer/ViewerApplication.cpp File Reference
Code/3DViewer/ViewerApplication.cpp File Reference
#include "ViewerApplication.h"
#include <Core/GEngine.h>
#include "EventsList.h"
#include "../Render/3D/3DRenderLayer.h"
#include "../Render/Interface/Button.h"
#include "../Render/Interface/Checkbox.h"
#include "UserInterface.h"
#include "../Render/3D/Plane.h"
#include "../Render/3D/WorldNode.h"
#include <Render/3D/VoxJect.h>
#include <math.h>
Functions
void toggleWireframeFn (IElements::Button *Btn)
Variables
const float viewerRotateSpeed = 50.0f
const float viewerMoveSpeed = 1000.0f
Function Documentation
void toggleWireframeFn (IElements::Button * Btn)
Definition at line 16 of file ViewerApplication.cpp.
References GRenderer::getRenderer(), and GRenderer::setRenderWireframeValue().
Referenced by ModelViewer::onLoad().
Variable Documentation
const float viewerMoveSpeed = 1000.0f
Definition at line 14 of file ViewerApplication.cpp.
Referenced by ModelViewer::updateApplication().
const float viewerRotateSpeed = 50.0f
Definition at line 13 of file ViewerApplication.cpp.
Referenced by ModelViewer::updateApplication().