Virtus: Code/Render/3D/WorldNode.cpp File Reference
Code/Render/3D/WorldNode.cpp File Reference
#include "WorldNode.h"
#include "../GRender.h"
#include <math.h>
#include "./3DRenderLayer.h"
Functions
float getXPoint (float phi, float theta, float radius)
float getYPoint (float phi, float theta, float radius)
float getZPoint (float phi, float theta, float radius)
float getUPoint (float phi, float theta, float r)
float getVPoint (float phi, float theta, float r)
unsigned int addToVertices (float phi, float theta, float r, float *Vertices, unsigned int currentVPtr)
unsigned int addToUV (float phi, float theta, float r, float *uvPtr, unsigned int currentUVP)
Variables
const unsigned int phi_stride = 10
const unsigned int theta_stride = 10
Function Documentation
unsigned int addToUV (float phi, float theta, float r, float * uvPtr, unsigned int currentUVP) [inline]
Definition at line 50 of file WorldNode.cpp.
References getYPoint().
Referenced by WorldNode::f_calculateVertices().
unsigned int addToVertices (float phi, float theta, float r, float * Vertices, unsigned int currentVPtr) [inline]
Definition at line 35 of file WorldNode.cpp.
References getXPoint(), getYPoint(), and getZPoint().
Referenced by WorldNode::f_calculateVertices().
float getUPoint (float phi, float theta, float r) [inline]
Definition at line 24 of file WorldNode.cpp.
float getVPoint (float phi, float theta, float r) [inline]
Definition at line 29 of file WorldNode.cpp.
float getXPoint (float phi, float theta, float radius) [inline]
Definition at line 9 of file WorldNode.cpp.
Referenced by addToVertices().
float getYPoint (float phi, float theta, float radius) [inline]
Definition at line 14 of file WorldNode.cpp.
Referenced by addToUV(), and addToVertices().
float getZPoint (float phi, float theta, float radius) [inline]
Definition at line 19 of file WorldNode.cpp.
Referenced by addToVertices().
Variable Documentation
const unsigned int phi_stride = 10
Definition at line 6 of file WorldNode.cpp.
Referenced by WorldNode::draw(), and WorldNode::f_calculateVertices().
const unsigned int theta_stride = 10
Definition at line 7 of file WorldNode.cpp.
Referenced by WorldNode::draw(), and WorldNode::f_calculateVertices().