#ifndef _3D_VIEWER_EVENT_LIST_
#define _3D_VIEWER_EVENT_LIST_

typedef enum {
    EVENT_POINTERDOWN,
    EVENT_POINTERUP,
    EVENT_POINTERMOTION,
    EVENT_MOVE_FORWARD,
    EVENT_MOVE_BACKWARD,
    EVENT_MOVE_FORWARD_STOP,
    EVENT_MOVE_BACKWARD_STOP,
    EVENT_ROTATE_LEFT,
    EVENT_ROTATE_LEFT_STOP,
    EVENT_ROTATE_RIGHT,
    EVENT_ROTATE_RIGHT_STOP,
    EVENT_MOVE_UP,
    EVENT_MOVE_UP_STOP,
    EVENT_MOVE_DOWN,
    EVENT_MOVE_DOWN_STOP,
    EVENT_WIREFRAME_TOGGLE,
    EVENT_CLOSE,
    EVENTS_END
} EVENT;

#endif //_3D_VIEWER_EVENT_LIST_
